// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: gachaMachine/gachaMachine.proto

package gachaMachine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GachaMachineService_CreateGachaPlayer_FullMethodName   = "/gachaMachine.GachaMachineService/CreateGachaPlayer"
	GachaMachineService_GetGachaPlayerInfo_FullMethodName  = "/gachaMachine.GachaMachineService/GetGachaPlayerInfo"
	GachaMachineService_AdjustPlayerGems_FullMethodName    = "/gachaMachine.GachaMachineService/AdjustPlayerGems"
	GachaMachineService_AdjustPlayerTickets_FullMethodName = "/gachaMachine.GachaMachineService/AdjustPlayerTickets"
	GachaMachineService_AddItemToPlayer_FullMethodName     = "/gachaMachine.GachaMachineService/AddItemToPlayer"
	GachaMachineService_CreateGachaPool_FullMethodName     = "/gachaMachine.GachaMachineService/CreateGachaPool"
	GachaMachineService_GetGachaPoolInfo_FullMethodName    = "/gachaMachine.GachaMachineService/GetGachaPoolInfo"
	GachaMachineService_GetAllGachaPools_FullMethodName    = "/gachaMachine.GachaMachineService/GetAllGachaPools"
	GachaMachineService_PullGacha_FullMethodName           = "/gachaMachine.GachaMachineService/PullGacha"
)

// GachaMachineServiceClient is the client API for GachaMachineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GachaMachineServiceClient interface {
	// player management
	CreateGachaPlayer(ctx context.Context, in *CreateGachaPlayerReq, opts ...grpc.CallOption) (*CreateGachaPlayerResp, error)
	GetGachaPlayerInfo(ctx context.Context, in *GetGachaPlayerInfoReq, opts ...grpc.CallOption) (*GetGachaPlayerInfoResp, error)
	AdjustPlayerGems(ctx context.Context, in *AdjustPlayerGemsReq, opts ...grpc.CallOption) (*AdjustPlayerGemsResp, error)
	AdjustPlayerTickets(ctx context.Context, in *AdjustPlayerTicketsReq, opts ...grpc.CallOption) (*AdjustPlayerTicketsResp, error)
	AddItemToPlayer(ctx context.Context, in *AddItemToPlayerReq, opts ...grpc.CallOption) (*AddItemToPlayerResp, error)
	// pool management
	CreateGachaPool(ctx context.Context, in *CreateGachaPoolReq, opts ...grpc.CallOption) (*CreateGachaPoolResp, error)
	GetGachaPoolInfo(ctx context.Context, in *GetGachaPoolInfoReq, opts ...grpc.CallOption) (*GetGachaPoolInfoResp, error)
	GetAllGachaPools(ctx context.Context, in *GetAllGachaPoolsReq, opts ...grpc.CallOption) (*GetAllGachaPoolsResp, error)
	// gacha operations
	PullGacha(ctx context.Context, in *PullGachaReq, opts ...grpc.CallOption) (*PullGachaResp, error)
}

type gachaMachineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGachaMachineServiceClient(cc grpc.ClientConnInterface) GachaMachineServiceClient {
	return &gachaMachineServiceClient{cc}
}

func (c *gachaMachineServiceClient) CreateGachaPlayer(ctx context.Context, in *CreateGachaPlayerReq, opts ...grpc.CallOption) (*CreateGachaPlayerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGachaPlayerResp)
	err := c.cc.Invoke(ctx, GachaMachineService_CreateGachaPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) GetGachaPlayerInfo(ctx context.Context, in *GetGachaPlayerInfoReq, opts ...grpc.CallOption) (*GetGachaPlayerInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGachaPlayerInfoResp)
	err := c.cc.Invoke(ctx, GachaMachineService_GetGachaPlayerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) AdjustPlayerGems(ctx context.Context, in *AdjustPlayerGemsReq, opts ...grpc.CallOption) (*AdjustPlayerGemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdjustPlayerGemsResp)
	err := c.cc.Invoke(ctx, GachaMachineService_AdjustPlayerGems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) AdjustPlayerTickets(ctx context.Context, in *AdjustPlayerTicketsReq, opts ...grpc.CallOption) (*AdjustPlayerTicketsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdjustPlayerTicketsResp)
	err := c.cc.Invoke(ctx, GachaMachineService_AdjustPlayerTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) AddItemToPlayer(ctx context.Context, in *AddItemToPlayerReq, opts ...grpc.CallOption) (*AddItemToPlayerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddItemToPlayerResp)
	err := c.cc.Invoke(ctx, GachaMachineService_AddItemToPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) CreateGachaPool(ctx context.Context, in *CreateGachaPoolReq, opts ...grpc.CallOption) (*CreateGachaPoolResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGachaPoolResp)
	err := c.cc.Invoke(ctx, GachaMachineService_CreateGachaPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) GetGachaPoolInfo(ctx context.Context, in *GetGachaPoolInfoReq, opts ...grpc.CallOption) (*GetGachaPoolInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGachaPoolInfoResp)
	err := c.cc.Invoke(ctx, GachaMachineService_GetGachaPoolInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) GetAllGachaPools(ctx context.Context, in *GetAllGachaPoolsReq, opts ...grpc.CallOption) (*GetAllGachaPoolsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllGachaPoolsResp)
	err := c.cc.Invoke(ctx, GachaMachineService_GetAllGachaPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) PullGacha(ctx context.Context, in *PullGachaReq, opts ...grpc.CallOption) (*PullGachaResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullGachaResp)
	err := c.cc.Invoke(ctx, GachaMachineService_PullGacha_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GachaMachineServiceServer is the server API for GachaMachineService service.
// All implementations must embed UnimplementedGachaMachineServiceServer
// for forward compatibility.
type GachaMachineServiceServer interface {
	// player management
	CreateGachaPlayer(context.Context, *CreateGachaPlayerReq) (*CreateGachaPlayerResp, error)
	GetGachaPlayerInfo(context.Context, *GetGachaPlayerInfoReq) (*GetGachaPlayerInfoResp, error)
	AdjustPlayerGems(context.Context, *AdjustPlayerGemsReq) (*AdjustPlayerGemsResp, error)
	AdjustPlayerTickets(context.Context, *AdjustPlayerTicketsReq) (*AdjustPlayerTicketsResp, error)
	AddItemToPlayer(context.Context, *AddItemToPlayerReq) (*AddItemToPlayerResp, error)
	// pool management
	CreateGachaPool(context.Context, *CreateGachaPoolReq) (*CreateGachaPoolResp, error)
	GetGachaPoolInfo(context.Context, *GetGachaPoolInfoReq) (*GetGachaPoolInfoResp, error)
	GetAllGachaPools(context.Context, *GetAllGachaPoolsReq) (*GetAllGachaPoolsResp, error)
	// gacha operations
	PullGacha(context.Context, *PullGachaReq) (*PullGachaResp, error)
	mustEmbedUnimplementedGachaMachineServiceServer()
}

// UnimplementedGachaMachineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGachaMachineServiceServer struct{}

func (UnimplementedGachaMachineServiceServer) CreateGachaPlayer(context.Context, *CreateGachaPlayerReq) (*CreateGachaPlayerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGachaPlayer not implemented")
}
func (UnimplementedGachaMachineServiceServer) GetGachaPlayerInfo(context.Context, *GetGachaPlayerInfoReq) (*GetGachaPlayerInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGachaPlayerInfo not implemented")
}
func (UnimplementedGachaMachineServiceServer) AdjustPlayerGems(context.Context, *AdjustPlayerGemsReq) (*AdjustPlayerGemsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdjustPlayerGems not implemented")
}
func (UnimplementedGachaMachineServiceServer) AdjustPlayerTickets(context.Context, *AdjustPlayerTicketsReq) (*AdjustPlayerTicketsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdjustPlayerTickets not implemented")
}
func (UnimplementedGachaMachineServiceServer) AddItemToPlayer(context.Context, *AddItemToPlayerReq) (*AddItemToPlayerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddItemToPlayer not implemented")
}
func (UnimplementedGachaMachineServiceServer) CreateGachaPool(context.Context, *CreateGachaPoolReq) (*CreateGachaPoolResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGachaPool not implemented")
}
func (UnimplementedGachaMachineServiceServer) GetGachaPoolInfo(context.Context, *GetGachaPoolInfoReq) (*GetGachaPoolInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGachaPoolInfo not implemented")
}
func (UnimplementedGachaMachineServiceServer) GetAllGachaPools(context.Context, *GetAllGachaPoolsReq) (*GetAllGachaPoolsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllGachaPools not implemented")
}
func (UnimplementedGachaMachineServiceServer) PullGacha(context.Context, *PullGachaReq) (*PullGachaResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullGacha not implemented")
}
func (UnimplementedGachaMachineServiceServer) mustEmbedUnimplementedGachaMachineServiceServer() {}
func (UnimplementedGachaMachineServiceServer) testEmbeddedByValue()                             {}

// UnsafeGachaMachineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GachaMachineServiceServer will
// result in compilation errors.
type UnsafeGachaMachineServiceServer interface {
	mustEmbedUnimplementedGachaMachineServiceServer()
}

func RegisterGachaMachineServiceServer(s grpc.ServiceRegistrar, srv GachaMachineServiceServer) {
	// If the following call pancis, it indicates UnimplementedGachaMachineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GachaMachineService_ServiceDesc, srv)
}

func _GachaMachineService_CreateGachaPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGachaPlayerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).CreateGachaPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_CreateGachaPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).CreateGachaPlayer(ctx, req.(*CreateGachaPlayerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_GetGachaPlayerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGachaPlayerInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).GetGachaPlayerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_GetGachaPlayerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).GetGachaPlayerInfo(ctx, req.(*GetGachaPlayerInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_AdjustPlayerGems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustPlayerGemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).AdjustPlayerGems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_AdjustPlayerGems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).AdjustPlayerGems(ctx, req.(*AdjustPlayerGemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_AdjustPlayerTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustPlayerTicketsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).AdjustPlayerTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_AdjustPlayerTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).AdjustPlayerTickets(ctx, req.(*AdjustPlayerTicketsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_AddItemToPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemToPlayerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).AddItemToPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_AddItemToPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).AddItemToPlayer(ctx, req.(*AddItemToPlayerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_CreateGachaPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGachaPoolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).CreateGachaPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_CreateGachaPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).CreateGachaPool(ctx, req.(*CreateGachaPoolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_GetGachaPoolInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGachaPoolInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).GetGachaPoolInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_GetGachaPoolInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).GetGachaPoolInfo(ctx, req.(*GetGachaPoolInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_GetAllGachaPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllGachaPoolsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).GetAllGachaPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_GetAllGachaPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).GetAllGachaPools(ctx, req.(*GetAllGachaPoolsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_PullGacha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullGachaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).PullGacha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_PullGacha_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).PullGacha(ctx, req.(*PullGachaReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GachaMachineService_ServiceDesc is the grpc.ServiceDesc for GachaMachineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GachaMachineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gachaMachine.GachaMachineService",
	HandlerType: (*GachaMachineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGachaPlayer",
			Handler:    _GachaMachineService_CreateGachaPlayer_Handler,
		},
		{
			MethodName: "GetGachaPlayerInfo",
			Handler:    _GachaMachineService_GetGachaPlayerInfo_Handler,
		},
		{
			MethodName: "AdjustPlayerGems",
			Handler:    _GachaMachineService_AdjustPlayerGems_Handler,
		},
		{
			MethodName: "AdjustPlayerTickets",
			Handler:    _GachaMachineService_AdjustPlayerTickets_Handler,
		},
		{
			MethodName: "AddItemToPlayer",
			Handler:    _GachaMachineService_AddItemToPlayer_Handler,
		},
		{
			MethodName: "CreateGachaPool",
			Handler:    _GachaMachineService_CreateGachaPool_Handler,
		},
		{
			MethodName: "GetGachaPoolInfo",
			Handler:    _GachaMachineService_GetGachaPoolInfo_Handler,
		},
		{
			MethodName: "GetAllGachaPools",
			Handler:    _GachaMachineService_GetAllGachaPools_Handler,
		},
		{
			MethodName: "PullGacha",
			Handler:    _GachaMachineService_PullGacha_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gachaMachine/gachaMachine.proto",
}
