// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: gachaMachine/gachaMachine.proto

package gachaMachine

import (
	player "github.com/Richard-inter/game/pkg/protocol/player"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ItemID          int64                  `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rarity          string                 `protobuf:"bytes,3,opt,name=rarity,proto3" json:"rarity,omitempty"`
	CatchPercentage int64                  `protobuf:"varint,5,opt,name=catchPercentage,proto3" json:"catchPercentage,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetItemID() int64 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *Item) GetCatchPercentage() int64 {
	if x != nil {
		return x.CatchPercentage
	}
	return 0
}

type GachaMachine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineID     int64                  `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Items         []*Item                `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	PriceTimesTen int64                  `protobuf:"varint,5,opt,name=priceTimesTen,proto3" json:"priceTimesTen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaMachine) Reset() {
	*x = GachaMachine{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaMachine) ProtoMessage() {}

func (x *GachaMachine) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaMachine.ProtoReflect.Descriptor instead.
func (*GachaMachine) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{1}
}

func (x *GachaMachine) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

func (x *GachaMachine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GachaMachine) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GachaMachine) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GachaMachine) GetPriceTimesTen() int64 {
	if x != nil {
		return x.PriceTimesTen
	}
	return 0
}

type GachaPlayer struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BasePlayer *player.Player         `protobuf:"bytes,1,opt,name=basePlayer,proto3" json:"basePlayer,omitempty"`
	// game specific attributes
	Coin          int64 `protobuf:"varint,2,opt,name=coin,proto3" json:"coin,omitempty"`
	Diamond       int64 `protobuf:"varint,3,opt,name=diamond,proto3" json:"diamond,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GachaPlayer) Reset() {
	*x = GachaPlayer{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GachaPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaPlayer) ProtoMessage() {}

func (x *GachaPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaPlayer.ProtoReflect.Descriptor instead.
func (*GachaPlayer) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{2}
}

func (x *GachaPlayer) GetBasePlayer() *player.Player {
	if x != nil {
		return x.BasePlayer
	}
	return nil
}

func (x *GachaPlayer) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *GachaPlayer) GetDiamond() int64 {
	if x != nil {
		return x.Diamond
	}
	return 0
}

type Items struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemID        int64                  `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Items) Reset() {
	*x = Items{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{3}
}

func (x *Items) GetItemID() int64 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

type CreateGachaMachineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Items         []*Items               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	PriceTimesTen int64                  `protobuf:"varint,4,opt,name=priceTimesTen,proto3" json:"priceTimesTen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGachaMachineReq) Reset() {
	*x = CreateGachaMachineReq{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGachaMachineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGachaMachineReq) ProtoMessage() {}

func (x *CreateGachaMachineReq) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGachaMachineReq.ProtoReflect.Descriptor instead.
func (*CreateGachaMachineReq) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{4}
}

func (x *CreateGachaMachineReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGachaMachineReq) GetItems() []*Items {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateGachaMachineReq) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateGachaMachineReq) GetPriceTimesTen() int64 {
	if x != nil {
		return x.PriceTimesTen
	}
	return 0
}

type CreateGachaMachineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *GachaMachine          `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGachaMachineResp) Reset() {
	*x = CreateGachaMachineResp{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGachaMachineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGachaMachineResp) ProtoMessage() {}

func (x *CreateGachaMachineResp) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGachaMachineResp.ProtoReflect.Descriptor instead.
func (*CreateGachaMachineResp) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{5}
}

func (x *CreateGachaMachineResp) GetMachine() *GachaMachine {
	if x != nil {
		return x.Machine
	}
	return nil
}

type CreateGachaItemReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rarity          string                 `protobuf:"bytes,2,opt,name=rarity,proto3" json:"rarity,omitempty"`
	CatchPercentage int64                  `protobuf:"varint,4,opt,name=catchPercentage,proto3" json:"catchPercentage,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateGachaItemReq) Reset() {
	*x = CreateGachaItemReq{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGachaItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGachaItemReq) ProtoMessage() {}

func (x *CreateGachaItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGachaItemReq.ProtoReflect.Descriptor instead.
func (*CreateGachaItemReq) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{6}
}

func (x *CreateGachaItemReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGachaItemReq) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *CreateGachaItemReq) GetCatchPercentage() int64 {
	if x != nil {
		return x.CatchPercentage
	}
	return 0
}

type CreateGachaItemsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GachaItems    []*CreateGachaItemReq  `protobuf:"bytes,1,rep,name=gachaItems,proto3" json:"gachaItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGachaItemsReq) Reset() {
	*x = CreateGachaItemsReq{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGachaItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGachaItemsReq) ProtoMessage() {}

func (x *CreateGachaItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGachaItemsReq.ProtoReflect.Descriptor instead.
func (*CreateGachaItemsReq) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{7}
}

func (x *CreateGachaItemsReq) GetGachaItems() []*CreateGachaItemReq {
	if x != nil {
		return x.GachaItems
	}
	return nil
}

type CreateGachaItemsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GachaItems    []*Item                `protobuf:"bytes,1,rep,name=gachaItems,proto3" json:"gachaItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGachaItemsResp) Reset() {
	*x = CreateGachaItemsResp{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGachaItemsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGachaItemsResp) ProtoMessage() {}

func (x *CreateGachaItemsResp) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGachaItemsResp.ProtoReflect.Descriptor instead.
func (*CreateGachaItemsResp) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{8}
}

func (x *CreateGachaItemsResp) GetGachaItems() []*Item {
	if x != nil {
		return x.GachaItems
	}
	return nil
}

type CreateGachaPlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *GachaPlayer           `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGachaPlayerReq) Reset() {
	*x = CreateGachaPlayerReq{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGachaPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGachaPlayerReq) ProtoMessage() {}

func (x *CreateGachaPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGachaPlayerReq.ProtoReflect.Descriptor instead.
func (*CreateGachaPlayerReq) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{9}
}

func (x *CreateGachaPlayerReq) GetPlayer() *GachaPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

type CreateGachaPlayerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *GachaPlayer           `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGachaPlayerResp) Reset() {
	*x = CreateGachaPlayerResp{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGachaPlayerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGachaPlayerResp) ProtoMessage() {}

func (x *CreateGachaPlayerResp) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGachaPlayerResp.ProtoReflect.Descriptor instead.
func (*CreateGachaPlayerResp) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{10}
}

func (x *CreateGachaPlayerResp) GetPlayer() *GachaPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

type AdjustPlayerCoinReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustPlayerCoinReq) Reset() {
	*x = AdjustPlayerCoinReq{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustPlayerCoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustPlayerCoinReq) ProtoMessage() {}

func (x *AdjustPlayerCoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustPlayerCoinReq.ProtoReflect.Descriptor instead.
func (*AdjustPlayerCoinReq) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{11}
}

func (x *AdjustPlayerCoinReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *AdjustPlayerCoinReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AdjustPlayerCoinReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type AdjustPlayerCoinResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerID       int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	AdjustedAmount int64                  `protobuf:"varint,2,opt,name=adjustedAmount,proto3" json:"adjustedAmount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdjustPlayerCoinResp) Reset() {
	*x = AdjustPlayerCoinResp{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustPlayerCoinResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustPlayerCoinResp) ProtoMessage() {}

func (x *AdjustPlayerCoinResp) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustPlayerCoinResp.ProtoReflect.Descriptor instead.
func (*AdjustPlayerCoinResp) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{12}
}

func (x *AdjustPlayerCoinResp) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *AdjustPlayerCoinResp) GetAdjustedAmount() int64 {
	if x != nil {
		return x.AdjustedAmount
	}
	return 0
}

type AdjustPlayerDiamondReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustPlayerDiamondReq) Reset() {
	*x = AdjustPlayerDiamondReq{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustPlayerDiamondReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustPlayerDiamondReq) ProtoMessage() {}

func (x *AdjustPlayerDiamondReq) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustPlayerDiamondReq.ProtoReflect.Descriptor instead.
func (*AdjustPlayerDiamondReq) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{13}
}

func (x *AdjustPlayerDiamondReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *AdjustPlayerDiamondReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AdjustPlayerDiamondReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type AdjustPlayerDiamondResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerID       int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	AdjustedAmount int64                  `protobuf:"varint,2,opt,name=adjustedAmount,proto3" json:"adjustedAmount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdjustPlayerDiamondResp) Reset() {
	*x = AdjustPlayerDiamondResp{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustPlayerDiamondResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustPlayerDiamondResp) ProtoMessage() {}

func (x *AdjustPlayerDiamondResp) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustPlayerDiamondResp.ProtoReflect.Descriptor instead.
func (*AdjustPlayerDiamondResp) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{14}
}

func (x *AdjustPlayerDiamondResp) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *AdjustPlayerDiamondResp) GetAdjustedAmount() int64 {
	if x != nil {
		return x.AdjustedAmount
	}
	return 0
}

type GetGachaPlayerInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGachaPlayerInfoReq) Reset() {
	*x = GetGachaPlayerInfoReq{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGachaPlayerInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGachaPlayerInfoReq) ProtoMessage() {}

func (x *GetGachaPlayerInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGachaPlayerInfoReq.ProtoReflect.Descriptor instead.
func (*GetGachaPlayerInfoReq) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{15}
}

func (x *GetGachaPlayerInfoReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

type GetGachaPlayerInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *GachaPlayer           `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGachaPlayerInfoResp) Reset() {
	*x = GetGachaPlayerInfoResp{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGachaPlayerInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGachaPlayerInfoResp) ProtoMessage() {}

func (x *GetGachaPlayerInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGachaPlayerInfoResp.ProtoReflect.Descriptor instead.
func (*GetGachaPlayerInfoResp) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{16}
}

func (x *GetGachaPlayerInfoResp) GetPlayer() *GachaPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

type GetGachaMachineInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineID     int64                  `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGachaMachineInfoReq) Reset() {
	*x = GetGachaMachineInfoReq{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGachaMachineInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGachaMachineInfoReq) ProtoMessage() {}

func (x *GetGachaMachineInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGachaMachineInfoReq.ProtoReflect.Descriptor instead.
func (*GetGachaMachineInfoReq) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{17}
}

func (x *GetGachaMachineInfoReq) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

type GetGachaMachineInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *GachaMachine          `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGachaMachineInfoResp) Reset() {
	*x = GetGachaMachineInfoResp{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGachaMachineInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGachaMachineInfoResp) ProtoMessage() {}

func (x *GetGachaMachineInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGachaMachineInfoResp.ProtoReflect.Descriptor instead.
func (*GetGachaMachineInfoResp) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{18}
}

func (x *GetGachaMachineInfoResp) GetMachine() *GachaMachine {
	if x != nil {
		return x.Machine
	}
	return nil
}

type GetPullResultReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	MachineID     int64                  `protobuf:"varint,2,opt,name=machineID,proto3" json:"machineID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPullResultReq) Reset() {
	*x = GetPullResultReq{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPullResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPullResultReq) ProtoMessage() {}

func (x *GetPullResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPullResultReq.ProtoReflect.Descriptor instead.
func (*GetPullResultReq) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{19}
}

func (x *GetPullResultReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *GetPullResultReq) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

type GetPullResultResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemID        int64                  `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPullResultResp) Reset() {
	*x = GetPullResultResp{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPullResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPullResultResp) ProtoMessage() {}

func (x *GetPullResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPullResultResp.ProtoReflect.Descriptor instead.
func (*GetPullResultResp) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{20}
}

func (x *GetPullResultResp) GetItemID() int64 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

type GetPullTimesTenResultReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	MachineID     int64                  `protobuf:"varint,2,opt,name=machineID,proto3" json:"machineID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPullTimesTenResultReq) Reset() {
	*x = GetPullTimesTenResultReq{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPullTimesTenResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPullTimesTenResultReq) ProtoMessage() {}

func (x *GetPullTimesTenResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPullTimesTenResultReq.ProtoReflect.Descriptor instead.
func (*GetPullTimesTenResultReq) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{21}
}

func (x *GetPullTimesTenResultReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *GetPullTimesTenResultReq) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

type GetPullTimesTenResultResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIDs       []int64                `protobuf:"varint,1,rep,packed,name=itemIDs,proto3" json:"itemIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPullTimesTenResultResp) Reset() {
	*x = GetPullTimesTenResultResp{}
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPullTimesTenResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPullTimesTenResultResp) ProtoMessage() {}

func (x *GetPullTimesTenResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_gachaMachine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPullTimesTenResultResp.ProtoReflect.Descriptor instead.
func (*GetPullTimesTenResultResp) Descriptor() ([]byte, []int) {
	return file_gachaMachine_gachaMachine_proto_rawDescGZIP(), []int{22}
}

func (x *GetPullTimesTenResultResp) GetItemIDs() []int64 {
	if x != nil {
		return x.ItemIDs
	}
	return nil
}

var File_gachaMachine_gachaMachine_proto protoreflect.FileDescriptor

const file_gachaMachine_gachaMachine_proto_rawDesc = "" +
	"\n" +
	"\x1fgachaMachine/gachaMachine.proto\x12\fgachaMachine\x1a\x13player/player.proto\"t\n" +
	"\x04Item\x12\x16\n" +
	"\x06itemID\x18\x01 \x01(\x03R\x06itemID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06rarity\x18\x03 \x01(\tR\x06rarity\x12(\n" +
	"\x0fcatchPercentage\x18\x05 \x01(\x03R\x0fcatchPercentage\"\xa6\x01\n" +
	"\fGachaMachine\x12\x1c\n" +
	"\tmachineID\x18\x01 \x01(\x03R\tmachineID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x05items\x18\x03 \x03(\v2\x12.gachaMachine.ItemR\x05items\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12$\n" +
	"\rpriceTimesTen\x18\x05 \x01(\x03R\rpriceTimesTen\"k\n" +
	"\vGachaPlayer\x12.\n" +
	"\n" +
	"basePlayer\x18\x01 \x01(\v2\x0e.player.PlayerR\n" +
	"basePlayer\x12\x12\n" +
	"\x04coin\x18\x02 \x01(\x03R\x04coin\x12\x18\n" +
	"\adiamond\x18\x03 \x01(\x03R\adiamond\"\x1f\n" +
	"\x05Items\x12\x16\n" +
	"\x06itemID\x18\x01 \x01(\x03R\x06itemID\"\x92\x01\n" +
	"\x15CreateGachaMachineReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.gachaMachine.ItemsR\x05items\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12$\n" +
	"\rpriceTimesTen\x18\x04 \x01(\x03R\rpriceTimesTen\"N\n" +
	"\x16CreateGachaMachineResp\x124\n" +
	"\amachine\x18\x01 \x01(\v2\x1a.gachaMachine.GachaMachineR\amachine\"j\n" +
	"\x12CreateGachaItemReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06rarity\x18\x02 \x01(\tR\x06rarity\x12(\n" +
	"\x0fcatchPercentage\x18\x04 \x01(\x03R\x0fcatchPercentage\"W\n" +
	"\x13CreateGachaItemsReq\x12@\n" +
	"\n" +
	"gachaItems\x18\x01 \x03(\v2 .gachaMachine.CreateGachaItemReqR\n" +
	"gachaItems\"J\n" +
	"\x14CreateGachaItemsResp\x122\n" +
	"\n" +
	"gachaItems\x18\x01 \x03(\v2\x12.gachaMachine.ItemR\n" +
	"gachaItems\"I\n" +
	"\x14CreateGachaPlayerReq\x121\n" +
	"\x06player\x18\x01 \x01(\v2\x19.gachaMachine.GachaPlayerR\x06player\"J\n" +
	"\x15CreateGachaPlayerResp\x121\n" +
	"\x06player\x18\x01 \x01(\v2\x19.gachaMachine.GachaPlayerR\x06player\"]\n" +
	"\x13AdjustPlayerCoinReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"Z\n" +
	"\x14AdjustPlayerCoinResp\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\x12&\n" +
	"\x0eadjustedAmount\x18\x02 \x01(\x03R\x0eadjustedAmount\"`\n" +
	"\x16AdjustPlayerDiamondReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"]\n" +
	"\x17AdjustPlayerDiamondResp\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\x12&\n" +
	"\x0eadjustedAmount\x18\x02 \x01(\x03R\x0eadjustedAmount\"3\n" +
	"\x15GetGachaPlayerInfoReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\"K\n" +
	"\x16GetGachaPlayerInfoResp\x121\n" +
	"\x06player\x18\x01 \x01(\v2\x19.gachaMachine.GachaPlayerR\x06player\"6\n" +
	"\x16GetGachaMachineInfoReq\x12\x1c\n" +
	"\tmachineID\x18\x01 \x01(\x03R\tmachineID\"O\n" +
	"\x17GetGachaMachineInfoResp\x124\n" +
	"\amachine\x18\x01 \x01(\v2\x1a.gachaMachine.GachaMachineR\amachine\"L\n" +
	"\x10GetPullResultReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\x12\x1c\n" +
	"\tmachineID\x18\x02 \x01(\x03R\tmachineID\"+\n" +
	"\x11GetPullResultResp\x12\x16\n" +
	"\x06itemID\x18\x01 \x01(\x03R\x06itemID\"T\n" +
	"\x18GetPullTimesTenResultReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\x12\x1c\n" +
	"\tmachineID\x18\x02 \x01(\x03R\tmachineID\"5\n" +
	"\x19GetPullTimesTenResultResp\x12\x18\n" +
	"\aitemIDs\x18\x01 \x03(\x03R\aitemIDs2\xe9\x06\n" +
	"\x13GachaMachineService\x12_\n" +
	"\x12CreateGachaMachine\x12#.gachaMachine.CreateGachaMachineReq\x1a$.gachaMachine.CreateGachaMachineResp\x12b\n" +
	"\x13GetGachaMachineInfo\x12$.gachaMachine.GetGachaMachineInfoReq\x1a%.gachaMachine.GetGachaMachineInfoResp\x12Y\n" +
	"\x10CreateGachaItems\x12!.gachaMachine.CreateGachaItemsReq\x1a\".gachaMachine.CreateGachaItemsResp\x12\\\n" +
	"\x11CreateGachaPlayer\x12\".gachaMachine.CreateGachaPlayerReq\x1a#.gachaMachine.CreateGachaPlayerResp\x12_\n" +
	"\x12GetGachaPlayerInfo\x12#.gachaMachine.GetGachaPlayerInfoReq\x1a$.gachaMachine.GetGachaPlayerInfoResp\x12Y\n" +
	"\x10AdjustPlayerCoin\x12!.gachaMachine.AdjustPlayerCoinReq\x1a\".gachaMachine.AdjustPlayerCoinResp\x12b\n" +
	"\x13AdjustPlayerDiamond\x12$.gachaMachine.AdjustPlayerDiamondReq\x1a%.gachaMachine.AdjustPlayerDiamondResp\x12P\n" +
	"\rGetPullResult\x12\x1e.gachaMachine.GetPullResultReq\x1a\x1f.gachaMachine.GetPullResultResp\x12b\n" +
	"\x0fGetPullTimesTen\x12&.gachaMachine.GetPullTimesTenResultReq\x1a'.gachaMachine.GetPullTimesTenResultRespB9Z7github.com/Richard-inter/game/pkg/protocol/gachaMachineb\x06proto3"

var (
	file_gachaMachine_gachaMachine_proto_rawDescOnce sync.Once
	file_gachaMachine_gachaMachine_proto_rawDescData []byte
)

func file_gachaMachine_gachaMachine_proto_rawDescGZIP() []byte {
	file_gachaMachine_gachaMachine_proto_rawDescOnce.Do(func() {
		file_gachaMachine_gachaMachine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gachaMachine_gachaMachine_proto_rawDesc), len(file_gachaMachine_gachaMachine_proto_rawDesc)))
	})
	return file_gachaMachine_gachaMachine_proto_rawDescData
}

var file_gachaMachine_gachaMachine_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_gachaMachine_gachaMachine_proto_goTypes = []any{
	(*Item)(nil),                      // 0: gachaMachine.Item
	(*GachaMachine)(nil),              // 1: gachaMachine.GachaMachine
	(*GachaPlayer)(nil),               // 2: gachaMachine.GachaPlayer
	(*Items)(nil),                     // 3: gachaMachine.Items
	(*CreateGachaMachineReq)(nil),     // 4: gachaMachine.CreateGachaMachineReq
	(*CreateGachaMachineResp)(nil),    // 5: gachaMachine.CreateGachaMachineResp
	(*CreateGachaItemReq)(nil),        // 6: gachaMachine.CreateGachaItemReq
	(*CreateGachaItemsReq)(nil),       // 7: gachaMachine.CreateGachaItemsReq
	(*CreateGachaItemsResp)(nil),      // 8: gachaMachine.CreateGachaItemsResp
	(*CreateGachaPlayerReq)(nil),      // 9: gachaMachine.CreateGachaPlayerReq
	(*CreateGachaPlayerResp)(nil),     // 10: gachaMachine.CreateGachaPlayerResp
	(*AdjustPlayerCoinReq)(nil),       // 11: gachaMachine.AdjustPlayerCoinReq
	(*AdjustPlayerCoinResp)(nil),      // 12: gachaMachine.AdjustPlayerCoinResp
	(*AdjustPlayerDiamondReq)(nil),    // 13: gachaMachine.AdjustPlayerDiamondReq
	(*AdjustPlayerDiamondResp)(nil),   // 14: gachaMachine.AdjustPlayerDiamondResp
	(*GetGachaPlayerInfoReq)(nil),     // 15: gachaMachine.GetGachaPlayerInfoReq
	(*GetGachaPlayerInfoResp)(nil),    // 16: gachaMachine.GetGachaPlayerInfoResp
	(*GetGachaMachineInfoReq)(nil),    // 17: gachaMachine.GetGachaMachineInfoReq
	(*GetGachaMachineInfoResp)(nil),   // 18: gachaMachine.GetGachaMachineInfoResp
	(*GetPullResultReq)(nil),          // 19: gachaMachine.GetPullResultReq
	(*GetPullResultResp)(nil),         // 20: gachaMachine.GetPullResultResp
	(*GetPullTimesTenResultReq)(nil),  // 21: gachaMachine.GetPullTimesTenResultReq
	(*GetPullTimesTenResultResp)(nil), // 22: gachaMachine.GetPullTimesTenResultResp
	(*player.Player)(nil),             // 23: player.Player
}
var file_gachaMachine_gachaMachine_proto_depIdxs = []int32{
	0,  // 0: gachaMachine.GachaMachine.items:type_name -> gachaMachine.Item
	23, // 1: gachaMachine.GachaPlayer.basePlayer:type_name -> player.Player
	3,  // 2: gachaMachine.CreateGachaMachineReq.items:type_name -> gachaMachine.Items
	1,  // 3: gachaMachine.CreateGachaMachineResp.machine:type_name -> gachaMachine.GachaMachine
	6,  // 4: gachaMachine.CreateGachaItemsReq.gachaItems:type_name -> gachaMachine.CreateGachaItemReq
	0,  // 5: gachaMachine.CreateGachaItemsResp.gachaItems:type_name -> gachaMachine.Item
	2,  // 6: gachaMachine.CreateGachaPlayerReq.player:type_name -> gachaMachine.GachaPlayer
	2,  // 7: gachaMachine.CreateGachaPlayerResp.player:type_name -> gachaMachine.GachaPlayer
	2,  // 8: gachaMachine.GetGachaPlayerInfoResp.player:type_name -> gachaMachine.GachaPlayer
	1,  // 9: gachaMachine.GetGachaMachineInfoResp.machine:type_name -> gachaMachine.GachaMachine
	4,  // 10: gachaMachine.GachaMachineService.CreateGachaMachine:input_type -> gachaMachine.CreateGachaMachineReq
	17, // 11: gachaMachine.GachaMachineService.GetGachaMachineInfo:input_type -> gachaMachine.GetGachaMachineInfoReq
	7,  // 12: gachaMachine.GachaMachineService.CreateGachaItems:input_type -> gachaMachine.CreateGachaItemsReq
	9,  // 13: gachaMachine.GachaMachineService.CreateGachaPlayer:input_type -> gachaMachine.CreateGachaPlayerReq
	15, // 14: gachaMachine.GachaMachineService.GetGachaPlayerInfo:input_type -> gachaMachine.GetGachaPlayerInfoReq
	11, // 15: gachaMachine.GachaMachineService.AdjustPlayerCoin:input_type -> gachaMachine.AdjustPlayerCoinReq
	13, // 16: gachaMachine.GachaMachineService.AdjustPlayerDiamond:input_type -> gachaMachine.AdjustPlayerDiamondReq
	19, // 17: gachaMachine.GachaMachineService.GetPullResult:input_type -> gachaMachine.GetPullResultReq
	21, // 18: gachaMachine.GachaMachineService.GetPullTimesTen:input_type -> gachaMachine.GetPullTimesTenResultReq
	5,  // 19: gachaMachine.GachaMachineService.CreateGachaMachine:output_type -> gachaMachine.CreateGachaMachineResp
	18, // 20: gachaMachine.GachaMachineService.GetGachaMachineInfo:output_type -> gachaMachine.GetGachaMachineInfoResp
	8,  // 21: gachaMachine.GachaMachineService.CreateGachaItems:output_type -> gachaMachine.CreateGachaItemsResp
	10, // 22: gachaMachine.GachaMachineService.CreateGachaPlayer:output_type -> gachaMachine.CreateGachaPlayerResp
	16, // 23: gachaMachine.GachaMachineService.GetGachaPlayerInfo:output_type -> gachaMachine.GetGachaPlayerInfoResp
	12, // 24: gachaMachine.GachaMachineService.AdjustPlayerCoin:output_type -> gachaMachine.AdjustPlayerCoinResp
	14, // 25: gachaMachine.GachaMachineService.AdjustPlayerDiamond:output_type -> gachaMachine.AdjustPlayerDiamondResp
	20, // 26: gachaMachine.GachaMachineService.GetPullResult:output_type -> gachaMachine.GetPullResultResp
	22, // 27: gachaMachine.GachaMachineService.GetPullTimesTen:output_type -> gachaMachine.GetPullTimesTenResultResp
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_gachaMachine_gachaMachine_proto_init() }
func file_gachaMachine_gachaMachine_proto_init() {
	if File_gachaMachine_gachaMachine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gachaMachine_gachaMachine_proto_rawDesc), len(file_gachaMachine_gachaMachine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gachaMachine_gachaMachine_proto_goTypes,
		DependencyIndexes: file_gachaMachine_gachaMachine_proto_depIdxs,
		MessageInfos:      file_gachaMachine_gachaMachine_proto_msgTypes,
	}.Build()
	File_gachaMachine_gachaMachine_proto = out.File
	file_gachaMachine_gachaMachine_proto_goTypes = nil
	file_gachaMachine_gachaMachine_proto_depIdxs = nil
}
