// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: gachaMachine/gachaMachine.proto

package gachaMachine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GachaMachineService_CreateGachaMachine_FullMethodName    = "/gachaMachine.GachaMachineService/CreateGachaMachine"
	GachaMachineService_GetGachaMachineInfo_FullMethodName   = "/gachaMachine.GachaMachineService/GetGachaMachineInfo"
	GachaMachineService_CreateGachaItems_FullMethodName      = "/gachaMachine.GachaMachineService/CreateGachaItems"
	GachaMachineService_CreateGachaPlayer_FullMethodName     = "/gachaMachine.GachaMachineService/CreateGachaPlayer"
	GachaMachineService_GetGachaPlayerInfo_FullMethodName    = "/gachaMachine.GachaMachineService/GetGachaPlayerInfo"
	GachaMachineService_AdjustPlayerCoin_FullMethodName      = "/gachaMachine.GachaMachineService/AdjustPlayerCoin"
	GachaMachineService_AdjustPlayerDiamond_FullMethodName   = "/gachaMachine.GachaMachineService/AdjustPlayerDiamond"
	GachaMachineService_GetPullResult_FullMethodName         = "/gachaMachine.GachaMachineService/GetPullResult"
	GachaMachineService_GetPullTimesTenResult_FullMethodName = "/gachaMachine.GachaMachineService/GetPullTimesTenResult"
)

// GachaMachineServiceClient is the client API for GachaMachineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GachaMachineServiceClient interface {
	// machine
	CreateGachaMachine(ctx context.Context, in *CreateGachaMachineReq, opts ...grpc.CallOption) (*CreateGachaMachineResp, error)
	GetGachaMachineInfo(ctx context.Context, in *GetGachaMachineInfoReq, opts ...grpc.CallOption) (*GetGachaMachineInfoResp, error)
	// item
	CreateGachaItems(ctx context.Context, in *CreateGachaItemsReq, opts ...grpc.CallOption) (*CreateGachaItemsResp, error)
	// player
	CreateGachaPlayer(ctx context.Context, in *CreateGachaPlayerReq, opts ...grpc.CallOption) (*CreateGachaPlayerResp, error)
	GetGachaPlayerInfo(ctx context.Context, in *GetGachaPlayerInfoReq, opts ...grpc.CallOption) (*GetGachaPlayerInfoResp, error)
	AdjustPlayerCoin(ctx context.Context, in *AdjustPlayerCoinReq, opts ...grpc.CallOption) (*AdjustPlayerCoinResp, error)
	AdjustPlayerDiamond(ctx context.Context, in *AdjustPlayerDiamondReq, opts ...grpc.CallOption) (*AdjustPlayerDiamondResp, error)
	// game
	GetPullResult(ctx context.Context, in *GetPullResultReq, opts ...grpc.CallOption) (*GetPullResultResp, error)
	GetPullTimesTenResult(ctx context.Context, in *GetPullTimesTenResultReq, opts ...grpc.CallOption) (*GetPullTimesTenResultResp, error)
}

type gachaMachineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGachaMachineServiceClient(cc grpc.ClientConnInterface) GachaMachineServiceClient {
	return &gachaMachineServiceClient{cc}
}

func (c *gachaMachineServiceClient) CreateGachaMachine(ctx context.Context, in *CreateGachaMachineReq, opts ...grpc.CallOption) (*CreateGachaMachineResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGachaMachineResp)
	err := c.cc.Invoke(ctx, GachaMachineService_CreateGachaMachine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) GetGachaMachineInfo(ctx context.Context, in *GetGachaMachineInfoReq, opts ...grpc.CallOption) (*GetGachaMachineInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGachaMachineInfoResp)
	err := c.cc.Invoke(ctx, GachaMachineService_GetGachaMachineInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) CreateGachaItems(ctx context.Context, in *CreateGachaItemsReq, opts ...grpc.CallOption) (*CreateGachaItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGachaItemsResp)
	err := c.cc.Invoke(ctx, GachaMachineService_CreateGachaItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) CreateGachaPlayer(ctx context.Context, in *CreateGachaPlayerReq, opts ...grpc.CallOption) (*CreateGachaPlayerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGachaPlayerResp)
	err := c.cc.Invoke(ctx, GachaMachineService_CreateGachaPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) GetGachaPlayerInfo(ctx context.Context, in *GetGachaPlayerInfoReq, opts ...grpc.CallOption) (*GetGachaPlayerInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGachaPlayerInfoResp)
	err := c.cc.Invoke(ctx, GachaMachineService_GetGachaPlayerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) AdjustPlayerCoin(ctx context.Context, in *AdjustPlayerCoinReq, opts ...grpc.CallOption) (*AdjustPlayerCoinResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdjustPlayerCoinResp)
	err := c.cc.Invoke(ctx, GachaMachineService_AdjustPlayerCoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) AdjustPlayerDiamond(ctx context.Context, in *AdjustPlayerDiamondReq, opts ...grpc.CallOption) (*AdjustPlayerDiamondResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdjustPlayerDiamondResp)
	err := c.cc.Invoke(ctx, GachaMachineService_AdjustPlayerDiamond_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) GetPullResult(ctx context.Context, in *GetPullResultReq, opts ...grpc.CallOption) (*GetPullResultResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPullResultResp)
	err := c.cc.Invoke(ctx, GachaMachineService_GetPullResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineServiceClient) GetPullTimesTenResult(ctx context.Context, in *GetPullTimesTenResultReq, opts ...grpc.CallOption) (*GetPullTimesTenResultResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPullTimesTenResultResp)
	err := c.cc.Invoke(ctx, GachaMachineService_GetPullTimesTenResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GachaMachineServiceServer is the server API for GachaMachineService service.
// All implementations must embed UnimplementedGachaMachineServiceServer
// for forward compatibility.
type GachaMachineServiceServer interface {
	// machine
	CreateGachaMachine(context.Context, *CreateGachaMachineReq) (*CreateGachaMachineResp, error)
	GetGachaMachineInfo(context.Context, *GetGachaMachineInfoReq) (*GetGachaMachineInfoResp, error)
	// item
	CreateGachaItems(context.Context, *CreateGachaItemsReq) (*CreateGachaItemsResp, error)
	// player
	CreateGachaPlayer(context.Context, *CreateGachaPlayerReq) (*CreateGachaPlayerResp, error)
	GetGachaPlayerInfo(context.Context, *GetGachaPlayerInfoReq) (*GetGachaPlayerInfoResp, error)
	AdjustPlayerCoin(context.Context, *AdjustPlayerCoinReq) (*AdjustPlayerCoinResp, error)
	AdjustPlayerDiamond(context.Context, *AdjustPlayerDiamondReq) (*AdjustPlayerDiamondResp, error)
	// game
	GetPullResult(context.Context, *GetPullResultReq) (*GetPullResultResp, error)
	GetPullTimesTenResult(context.Context, *GetPullTimesTenResultReq) (*GetPullTimesTenResultResp, error)
	mustEmbedUnimplementedGachaMachineServiceServer()
}

// UnimplementedGachaMachineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGachaMachineServiceServer struct{}

func (UnimplementedGachaMachineServiceServer) CreateGachaMachine(context.Context, *CreateGachaMachineReq) (*CreateGachaMachineResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGachaMachine not implemented")
}
func (UnimplementedGachaMachineServiceServer) GetGachaMachineInfo(context.Context, *GetGachaMachineInfoReq) (*GetGachaMachineInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGachaMachineInfo not implemented")
}
func (UnimplementedGachaMachineServiceServer) CreateGachaItems(context.Context, *CreateGachaItemsReq) (*CreateGachaItemsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGachaItems not implemented")
}
func (UnimplementedGachaMachineServiceServer) CreateGachaPlayer(context.Context, *CreateGachaPlayerReq) (*CreateGachaPlayerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGachaPlayer not implemented")
}
func (UnimplementedGachaMachineServiceServer) GetGachaPlayerInfo(context.Context, *GetGachaPlayerInfoReq) (*GetGachaPlayerInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGachaPlayerInfo not implemented")
}
func (UnimplementedGachaMachineServiceServer) AdjustPlayerCoin(context.Context, *AdjustPlayerCoinReq) (*AdjustPlayerCoinResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdjustPlayerCoin not implemented")
}
func (UnimplementedGachaMachineServiceServer) AdjustPlayerDiamond(context.Context, *AdjustPlayerDiamondReq) (*AdjustPlayerDiamondResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdjustPlayerDiamond not implemented")
}
func (UnimplementedGachaMachineServiceServer) GetPullResult(context.Context, *GetPullResultReq) (*GetPullResultResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPullResult not implemented")
}
func (UnimplementedGachaMachineServiceServer) GetPullTimesTenResult(context.Context, *GetPullTimesTenResultReq) (*GetPullTimesTenResultResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPullTimesTenResult not implemented")
}
func (UnimplementedGachaMachineServiceServer) mustEmbedUnimplementedGachaMachineServiceServer() {}
func (UnimplementedGachaMachineServiceServer) testEmbeddedByValue()                             {}

// UnsafeGachaMachineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GachaMachineServiceServer will
// result in compilation errors.
type UnsafeGachaMachineServiceServer interface {
	mustEmbedUnimplementedGachaMachineServiceServer()
}

func RegisterGachaMachineServiceServer(s grpc.ServiceRegistrar, srv GachaMachineServiceServer) {
	// If the following call pancis, it indicates UnimplementedGachaMachineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GachaMachineService_ServiceDesc, srv)
}

func _GachaMachineService_CreateGachaMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGachaMachineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).CreateGachaMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_CreateGachaMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).CreateGachaMachine(ctx, req.(*CreateGachaMachineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_GetGachaMachineInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGachaMachineInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).GetGachaMachineInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_GetGachaMachineInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).GetGachaMachineInfo(ctx, req.(*GetGachaMachineInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_CreateGachaItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGachaItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).CreateGachaItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_CreateGachaItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).CreateGachaItems(ctx, req.(*CreateGachaItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_CreateGachaPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGachaPlayerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).CreateGachaPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_CreateGachaPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).CreateGachaPlayer(ctx, req.(*CreateGachaPlayerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_GetGachaPlayerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGachaPlayerInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).GetGachaPlayerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_GetGachaPlayerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).GetGachaPlayerInfo(ctx, req.(*GetGachaPlayerInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_AdjustPlayerCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustPlayerCoinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).AdjustPlayerCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_AdjustPlayerCoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).AdjustPlayerCoin(ctx, req.(*AdjustPlayerCoinReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_AdjustPlayerDiamond_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustPlayerDiamondReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).AdjustPlayerDiamond(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_AdjustPlayerDiamond_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).AdjustPlayerDiamond(ctx, req.(*AdjustPlayerDiamondReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_GetPullResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPullResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).GetPullResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_GetPullResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).GetPullResult(ctx, req.(*GetPullResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineService_GetPullTimesTenResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPullTimesTenResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineServiceServer).GetPullTimesTenResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineService_GetPullTimesTenResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineServiceServer).GetPullTimesTenResult(ctx, req.(*GetPullTimesTenResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GachaMachineService_ServiceDesc is the grpc.ServiceDesc for GachaMachineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GachaMachineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gachaMachine.GachaMachineService",
	HandlerType: (*GachaMachineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGachaMachine",
			Handler:    _GachaMachineService_CreateGachaMachine_Handler,
		},
		{
			MethodName: "GetGachaMachineInfo",
			Handler:    _GachaMachineService_GetGachaMachineInfo_Handler,
		},
		{
			MethodName: "CreateGachaItems",
			Handler:    _GachaMachineService_CreateGachaItems_Handler,
		},
		{
			MethodName: "CreateGachaPlayer",
			Handler:    _GachaMachineService_CreateGachaPlayer_Handler,
		},
		{
			MethodName: "GetGachaPlayerInfo",
			Handler:    _GachaMachineService_GetGachaPlayerInfo_Handler,
		},
		{
			MethodName: "AdjustPlayerCoin",
			Handler:    _GachaMachineService_AdjustPlayerCoin_Handler,
		},
		{
			MethodName: "AdjustPlayerDiamond",
			Handler:    _GachaMachineService_AdjustPlayerDiamond_Handler,
		},
		{
			MethodName: "GetPullResult",
			Handler:    _GachaMachineService_GetPullResult_Handler,
		},
		{
			MethodName: "GetPullTimesTenResult",
			Handler:    _GachaMachineService_GetPullTimesTenResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gachaMachine/gachaMachine.proto",
}
