// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gachaMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetMachineInfoWsReq struct {
	_tab flatbuffers.Table
}

func GetRootAsGetMachineInfoWsReq(buf []byte, offset flatbuffers.UOffsetT) *GetMachineInfoWsReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetMachineInfoWsReq{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetMachineInfoWsReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetMachineInfoWsReq(buf []byte, offset flatbuffers.UOffsetT) *GetMachineInfoWsReq {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetMachineInfoWsReq{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetMachineInfoWsReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetMachineInfoWsReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetMachineInfoWsReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetMachineInfoWsReq) MachineId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetMachineInfoWsReq) MutateMachineId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func GetMachineInfoWsReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetMachineInfoWsReqAddMachineId(builder *flatbuffers.Builder, machineId int64) {
	builder.PrependInt64Slot(0, machineId, 0)
}
func GetMachineInfoWsReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
