// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gachaMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetPlayerInfoWsResp struct {
	_tab flatbuffers.Table
}

func GetRootAsGetPlayerInfoWsResp(buf []byte, offset flatbuffers.UOffsetT) *GetPlayerInfoWsResp {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetPlayerInfoWsResp{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetPlayerInfoWsRespBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetPlayerInfoWsResp(buf []byte, offset flatbuffers.UOffsetT) *GetPlayerInfoWsResp {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetPlayerInfoWsResp{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetPlayerInfoWsRespBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetPlayerInfoWsResp) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetPlayerInfoWsResp) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetPlayerInfoWsResp) PlayerId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetPlayerInfoWsResp) MutatePlayerId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *GetPlayerInfoWsResp) Username() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GetPlayerInfoWsResp) Coin() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetPlayerInfoWsResp) MutateCoin(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *GetPlayerInfoWsResp) Diamond() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetPlayerInfoWsResp) MutateDiamond(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func GetPlayerInfoWsRespStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func GetPlayerInfoWsRespAddPlayerId(builder *flatbuffers.Builder, playerId int64) {
	builder.PrependInt64Slot(0, playerId, 0)
}
func GetPlayerInfoWsRespAddUsername(builder *flatbuffers.Builder, username flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(username), 0)
}
func GetPlayerInfoWsRespAddCoin(builder *flatbuffers.Builder, coin int64) {
	builder.PrependInt64Slot(2, coin, 0)
}
func GetPlayerInfoWsRespAddDiamond(builder *flatbuffers.Builder, diamond int64) {
	builder.PrependInt64Slot(3, diamond, 0)
}
func GetPlayerInfoWsRespEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
