// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gachaMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetPlayerPullHistoryWsResp struct {
	_tab flatbuffers.Table
}

func GetRootAsGetPlayerPullHistoryWsResp(buf []byte, offset flatbuffers.UOffsetT) *GetPlayerPullHistoryWsResp {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetPlayerPullHistoryWsResp{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetPlayerPullHistoryWsRespBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetPlayerPullHistoryWsResp(buf []byte, offset flatbuffers.UOffsetT) *GetPlayerPullHistoryWsResp {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetPlayerPullHistoryWsResp{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetPlayerPullHistoryWsRespBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetPlayerPullHistoryWsResp) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetPlayerPullHistoryWsResp) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetPlayerPullHistoryWsResp) PlayerId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetPlayerPullHistoryWsResp) MutatePlayerId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *GetPlayerPullHistoryWsResp) Sessions(obj *PullSession, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *GetPlayerPullHistoryWsResp) SessionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func GetPlayerPullHistoryWsRespStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GetPlayerPullHistoryWsRespAddPlayerId(builder *flatbuffers.Builder, playerId int64) {
	builder.PrependInt64Slot(0, playerId, 0)
}
func GetPlayerPullHistoryWsRespAddSessions(builder *flatbuffers.Builder, sessions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(sessions), 0)
}
func GetPlayerPullHistoryWsRespStartSessionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GetPlayerPullHistoryWsRespEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
