// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gachaMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetPullResultWsReq struct {
	_tab flatbuffers.Table
}

func GetRootAsGetPullResultWsReq(buf []byte, offset flatbuffers.UOffsetT) *GetPullResultWsReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetPullResultWsReq{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetPullResultWsReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetPullResultWsReq(buf []byte, offset flatbuffers.UOffsetT) *GetPullResultWsReq {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetPullResultWsReq{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetPullResultWsReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetPullResultWsReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetPullResultWsReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetPullResultWsReq) PlayerId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetPullResultWsReq) MutatePlayerId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *GetPullResultWsReq) MachineId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetPullResultWsReq) MutateMachineId(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *GetPullResultWsReq) PullCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetPullResultWsReq) MutatePullCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func GetPullResultWsReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func GetPullResultWsReqAddPlayerId(builder *flatbuffers.Builder, playerId int64) {
	builder.PrependInt64Slot(0, playerId, 0)
}
func GetPullResultWsReqAddMachineId(builder *flatbuffers.Builder, machineId int64) {
	builder.PrependInt64Slot(1, machineId, 0)
}
func GetPullResultWsReqAddPullCount(builder *flatbuffers.Builder, pullCount int32) {
	builder.PrependInt32Slot(2, pullCount, 0)
}
func GetPullResultWsReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
