// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gachaMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetPullResultWsResp struct {
	_tab flatbuffers.Table
}

func GetRootAsGetPullResultWsResp(buf []byte, offset flatbuffers.UOffsetT) *GetPullResultWsResp {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetPullResultWsResp{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetPullResultWsRespBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetPullResultWsResp(buf []byte, offset flatbuffers.UOffsetT) *GetPullResultWsResp {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetPullResultWsResp{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetPullResultWsRespBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetPullResultWsResp) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetPullResultWsResp) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetPullResultWsResp) ItemIds(j int) int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *GetPullResultWsResp) ItemIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GetPullResultWsResp) MutateItemIds(j int, n int64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func GetPullResultWsRespStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetPullResultWsRespAddItemIds(builder *flatbuffers.Builder, itemIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(itemIds), 0)
}
func GetPullResultWsRespStartItemIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func GetPullResultWsRespEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
