// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gachaMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetPlayerPullHistoryWsReq struct {
	_tab flatbuffers.Table
}

func GetRootAsGetPlayerPullHistoryWsReq(buf []byte, offset flatbuffers.UOffsetT) *GetPlayerPullHistoryWsReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetPlayerPullHistoryWsReq{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetPlayerPullHistoryWsReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetPlayerPullHistoryWsReq(buf []byte, offset flatbuffers.UOffsetT) *GetPlayerPullHistoryWsReq {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetPlayerPullHistoryWsReq{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetPlayerPullHistoryWsReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetPlayerPullHistoryWsReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetPlayerPullHistoryWsReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetPlayerPullHistoryWsReq) PlayerId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetPlayerPullHistoryWsReq) MutatePlayerId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func GetPlayerPullHistoryWsReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetPlayerPullHistoryWsReqAddPlayerId(builder *flatbuffers.Builder, playerId int64) {
	builder.PrependInt64Slot(0, playerId, 0)
}
func GetPlayerPullHistoryWsReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
