// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gachaMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetPlayerInfoWsReq struct {
	_tab flatbuffers.Table
}

func GetRootAsGetPlayerInfoWsReq(buf []byte, offset flatbuffers.UOffsetT) *GetPlayerInfoWsReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetPlayerInfoWsReq{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetPlayerInfoWsReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetPlayerInfoWsReq(buf []byte, offset flatbuffers.UOffsetT) *GetPlayerInfoWsReq {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetPlayerInfoWsReq{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetPlayerInfoWsReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetPlayerInfoWsReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetPlayerInfoWsReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetPlayerInfoWsReq) PlayerId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetPlayerInfoWsReq) MutatePlayerId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func GetPlayerInfoWsReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetPlayerInfoWsReqAddPlayerId(builder *flatbuffers.Builder, playerId int64) {
	builder.PrependInt64Slot(0, playerId, 0)
}
func GetPlayerInfoWsReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
