// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gachaMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Items struct {
	_tab flatbuffers.Table
}

func GetRootAsItems(buf []byte, offset flatbuffers.UOffsetT) *Items {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Items{}
	x.Init(buf, n+offset)
	return x
}

func FinishItemsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsItems(buf []byte, offset flatbuffers.UOffsetT) *Items {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Items{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedItemsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Items) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Items) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Items) ItemId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Items) MutateItemId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *Items) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Items) Rarity() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Items) PullWeight() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Items) MutatePullWeight(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func ItemsStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ItemsAddItemId(builder *flatbuffers.Builder, itemId int64) {
	builder.PrependInt64Slot(0, itemId, 0)
}
func ItemsAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func ItemsAddRarity(builder *flatbuffers.Builder, rarity flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(rarity), 0)
}
func ItemsAddPullWeight(builder *flatbuffers.Builder, pullWeight int32) {
	builder.PrependInt32Slot(3, pullWeight, 0)
}
func ItemsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
