// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gachaMachine

import "strconv"

type MessageType int8

const (
	MessageTypeGetPullResultWsReq   MessageType = 0
	MessageTypeGetPullResultWsResp  MessageType = 1
	MessageTypeGetPlayerInfoWsReq   MessageType = 2
	MessageTypeGetPlayerInfoWsResp  MessageType = 3
	MessageTypeGetMachineInfoWsReq  MessageType = 4
	MessageTypeGetMachineInfoWsResp MessageType = 5
	MessageTypeErrorResp            MessageType = 100
)

var EnumNamesMessageType = map[MessageType]string{
	MessageTypeGetPullResultWsReq:   "GetPullResultWsReq",
	MessageTypeGetPullResultWsResp:  "GetPullResultWsResp",
	MessageTypeGetPlayerInfoWsReq:   "GetPlayerInfoWsReq",
	MessageTypeGetPlayerInfoWsResp:  "GetPlayerInfoWsResp",
	MessageTypeGetMachineInfoWsReq:  "GetMachineInfoWsReq",
	MessageTypeGetMachineInfoWsResp: "GetMachineInfoWsResp",
	MessageTypeErrorResp:            "ErrorResp",
}

var EnumValuesMessageType = map[string]MessageType{
	"GetPullResultWsReq":   MessageTypeGetPullResultWsReq,
	"GetPullResultWsResp":  MessageTypeGetPullResultWsResp,
	"GetPlayerInfoWsReq":   MessageTypeGetPlayerInfoWsReq,
	"GetPlayerInfoWsResp":  MessageTypeGetPlayerInfoWsResp,
	"GetMachineInfoWsReq":  MessageTypeGetMachineInfoWsReq,
	"GetMachineInfoWsResp": MessageTypeGetMachineInfoWsResp,
	"ErrorResp":            MessageTypeErrorResp,
}

func (v MessageType) String() string {
	if s, ok := EnumNamesMessageType[v]; ok {
		return s
	}
	return "MessageType(" + strconv.FormatInt(int64(v), 10) + ")"
}
