// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gachaMachine

import "strconv"

type MessageType int8

const (
	MessageTypeGetPullResultWs  MessageType = 0
	MessageTypeGetPlayerInfoWs  MessageType = 1
	MessageTypeGetMachineInfoWs MessageType = 2
	MessageTypeErrorResp        MessageType = 100
)

var EnumNamesMessageType = map[MessageType]string{
	MessageTypeGetPullResultWs:  "GetPullResultWs",
	MessageTypeGetPlayerInfoWs:  "GetPlayerInfoWs",
	MessageTypeGetMachineInfoWs: "GetMachineInfoWs",
	MessageTypeErrorResp:        "ErrorResp",
}

var EnumValuesMessageType = map[string]MessageType{
	"GetPullResultWs":  MessageTypeGetPullResultWs,
	"GetPlayerInfoWs":  MessageTypeGetPlayerInfoWs,
	"GetMachineInfoWs": MessageTypeGetMachineInfoWs,
	"ErrorResp":        MessageTypeErrorResp,
}

func (v MessageType) String() string {
	if s, ok := EnumNamesMessageType[v]; ok {
		return s
	}
	return "MessageType(" + strconv.FormatInt(int64(v), 10) + ")"
}
