// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gachaMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PullSession struct {
	_tab flatbuffers.Table
}

func GetRootAsPullSession(buf []byte, offset flatbuffers.UOffsetT) *PullSession {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PullSession{}
	x.Init(buf, n+offset)
	return x
}

func FinishPullSessionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPullSession(buf []byte, offset flatbuffers.UOffsetT) *PullSession {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PullSession{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPullSessionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PullSession) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PullSession) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PullSession) SessionId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PullSession) MutateSessionId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *PullSession) MachineId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PullSession) MutateMachineId(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *PullSession) PullCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PullSession) MutatePullCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *PullSession) ItemsPulled(obj *PullHistoryItem, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PullSession) ItemsPulledLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PullSessionStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func PullSessionAddSessionId(builder *flatbuffers.Builder, sessionId int64) {
	builder.PrependInt64Slot(0, sessionId, 0)
}
func PullSessionAddMachineId(builder *flatbuffers.Builder, machineId int64) {
	builder.PrependInt64Slot(1, machineId, 0)
}
func PullSessionAddPullCount(builder *flatbuffers.Builder, pullCount int32) {
	builder.PrependInt32Slot(2, pullCount, 0)
}
func PullSessionAddItemsPulled(builder *flatbuffers.Builder, itemsPulled flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(itemsPulled), 0)
}
func PullSessionStartItemsPulledVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PullSessionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
