// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: gachaMachine_Websocket/gachaMachine_runtime.proto

package gachaMachine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GachaMachineRuntimeService_GetPullResultWs_FullMethodName  = "/gachaMachine.GachaMachineRuntimeService/GetPullResultWs"
	GachaMachineRuntimeService_GetPlayerInfoWs_FullMethodName  = "/gachaMachine.GachaMachineRuntimeService/GetPlayerInfoWs"
	GachaMachineRuntimeService_GetMachineInfoWs_FullMethodName = "/gachaMachine.GachaMachineRuntimeService/GetMachineInfoWs"
)

// GachaMachineRuntimeServiceClient is the client API for GachaMachineRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GachaMachineRuntimeServiceClient interface {
	GetPullResultWs(ctx context.Context, in *RuntimeRequest, opts ...grpc.CallOption) (*RuntimeResponse, error)
	GetPlayerInfoWs(ctx context.Context, in *RuntimeRequest, opts ...grpc.CallOption) (*RuntimeResponse, error)
	GetMachineInfoWs(ctx context.Context, in *RuntimeRequest, opts ...grpc.CallOption) (*RuntimeResponse, error)
}

type gachaMachineRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGachaMachineRuntimeServiceClient(cc grpc.ClientConnInterface) GachaMachineRuntimeServiceClient {
	return &gachaMachineRuntimeServiceClient{cc}
}

func (c *gachaMachineRuntimeServiceClient) GetPullResultWs(ctx context.Context, in *RuntimeRequest, opts ...grpc.CallOption) (*RuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeResponse)
	err := c.cc.Invoke(ctx, GachaMachineRuntimeService_GetPullResultWs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineRuntimeServiceClient) GetPlayerInfoWs(ctx context.Context, in *RuntimeRequest, opts ...grpc.CallOption) (*RuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeResponse)
	err := c.cc.Invoke(ctx, GachaMachineRuntimeService_GetPlayerInfoWs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gachaMachineRuntimeServiceClient) GetMachineInfoWs(ctx context.Context, in *RuntimeRequest, opts ...grpc.CallOption) (*RuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeResponse)
	err := c.cc.Invoke(ctx, GachaMachineRuntimeService_GetMachineInfoWs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GachaMachineRuntimeServiceServer is the server API for GachaMachineRuntimeService service.
// All implementations must embed UnimplementedGachaMachineRuntimeServiceServer
// for forward compatibility.
type GachaMachineRuntimeServiceServer interface {
	GetPullResultWs(context.Context, *RuntimeRequest) (*RuntimeResponse, error)
	GetPlayerInfoWs(context.Context, *RuntimeRequest) (*RuntimeResponse, error)
	GetMachineInfoWs(context.Context, *RuntimeRequest) (*RuntimeResponse, error)
	mustEmbedUnimplementedGachaMachineRuntimeServiceServer()
}

// UnimplementedGachaMachineRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGachaMachineRuntimeServiceServer struct{}

func (UnimplementedGachaMachineRuntimeServiceServer) GetPullResultWs(context.Context, *RuntimeRequest) (*RuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPullResultWs not implemented")
}
func (UnimplementedGachaMachineRuntimeServiceServer) GetPlayerInfoWs(context.Context, *RuntimeRequest) (*RuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerInfoWs not implemented")
}
func (UnimplementedGachaMachineRuntimeServiceServer) GetMachineInfoWs(context.Context, *RuntimeRequest) (*RuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMachineInfoWs not implemented")
}
func (UnimplementedGachaMachineRuntimeServiceServer) mustEmbedUnimplementedGachaMachineRuntimeServiceServer() {
}
func (UnimplementedGachaMachineRuntimeServiceServer) testEmbeddedByValue() {}

// UnsafeGachaMachineRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GachaMachineRuntimeServiceServer will
// result in compilation errors.
type UnsafeGachaMachineRuntimeServiceServer interface {
	mustEmbedUnimplementedGachaMachineRuntimeServiceServer()
}

func RegisterGachaMachineRuntimeServiceServer(s grpc.ServiceRegistrar, srv GachaMachineRuntimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedGachaMachineRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GachaMachineRuntimeService_ServiceDesc, srv)
}

func _GachaMachineRuntimeService_GetPullResultWs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineRuntimeServiceServer).GetPullResultWs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineRuntimeService_GetPullResultWs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineRuntimeServiceServer).GetPullResultWs(ctx, req.(*RuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineRuntimeService_GetPlayerInfoWs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineRuntimeServiceServer).GetPlayerInfoWs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineRuntimeService_GetPlayerInfoWs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineRuntimeServiceServer).GetPlayerInfoWs(ctx, req.(*RuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GachaMachineRuntimeService_GetMachineInfoWs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GachaMachineRuntimeServiceServer).GetMachineInfoWs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GachaMachineRuntimeService_GetMachineInfoWs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GachaMachineRuntimeServiceServer).GetMachineInfoWs(ctx, req.(*RuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GachaMachineRuntimeService_ServiceDesc is the grpc.ServiceDesc for GachaMachineRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GachaMachineRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gachaMachine.GachaMachineRuntimeService",
	HandlerType: (*GachaMachineRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPullResultWs",
			Handler:    _GachaMachineRuntimeService_GetPullResultWs_Handler,
		},
		{
			MethodName: "GetPlayerInfoWs",
			Handler:    _GachaMachineRuntimeService_GetPlayerInfoWs_Handler,
		},
		{
			MethodName: "GetMachineInfoWs",
			Handler:    _GachaMachineRuntimeService_GetMachineInfoWs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gachaMachine_Websocket/gachaMachine_runtime.proto",
}
