// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: gachaMachine_Websocket/gachaMachine_runtime.proto

package gachaMachine_Websocket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeRequest) Reset() {
	*x = RuntimeRequest{}
	mi := &file_gachaMachine_Websocket_gachaMachine_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeRequest) ProtoMessage() {}

func (x *RuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_Websocket_gachaMachine_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeRequest.ProtoReflect.Descriptor instead.
func (*RuntimeRequest) Descriptor() ([]byte, []int) {
	return file_gachaMachine_Websocket_gachaMachine_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RuntimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeResponse) Reset() {
	*x = RuntimeResponse{}
	mi := &file_gachaMachine_Websocket_gachaMachine_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeResponse) ProtoMessage() {}

func (x *RuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gachaMachine_Websocket_gachaMachine_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeResponse.ProtoReflect.Descriptor instead.
func (*RuntimeResponse) Descriptor() ([]byte, []int) {
	return file_gachaMachine_Websocket_gachaMachine_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_gachaMachine_Websocket_gachaMachine_runtime_proto protoreflect.FileDescriptor

const file_gachaMachine_Websocket_gachaMachine_runtime_proto_rawDesc = "" +
	"\n" +
	"1gachaMachine_Websocket/gachaMachine_runtime.proto\x12\x14gachaMachine.runtime\"*\n" +
	"\x0eRuntimeRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"+\n" +
	"\x0fRuntimeResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload2\xbd\x02\n" +
	"\x1aGachaMachineRuntimeService\x12^\n" +
	"\x0fGetPullResultWs\x12$.gachaMachine.runtime.RuntimeRequest\x1a%.gachaMachine.runtime.RuntimeResponse\x12^\n" +
	"\x0fGetPlayerInfoWs\x12$.gachaMachine.runtime.RuntimeRequest\x1a%.gachaMachine.runtime.RuntimeResponse\x12_\n" +
	"\x10GetMachineInfoWs\x12$.gachaMachine.runtime.RuntimeRequest\x1a%.gachaMachine.runtime.RuntimeResponseBCZAgithub.com/Richard-inter/game/pkg/protocol/gachaMachine_Websocketb\x06proto3"

var (
	file_gachaMachine_Websocket_gachaMachine_runtime_proto_rawDescOnce sync.Once
	file_gachaMachine_Websocket_gachaMachine_runtime_proto_rawDescData []byte
)

func file_gachaMachine_Websocket_gachaMachine_runtime_proto_rawDescGZIP() []byte {
	file_gachaMachine_Websocket_gachaMachine_runtime_proto_rawDescOnce.Do(func() {
		file_gachaMachine_Websocket_gachaMachine_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gachaMachine_Websocket_gachaMachine_runtime_proto_rawDesc), len(file_gachaMachine_Websocket_gachaMachine_runtime_proto_rawDesc)))
	})
	return file_gachaMachine_Websocket_gachaMachine_runtime_proto_rawDescData
}

var file_gachaMachine_Websocket_gachaMachine_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gachaMachine_Websocket_gachaMachine_runtime_proto_goTypes = []any{
	(*RuntimeRequest)(nil),  // 0: gachaMachine.runtime.RuntimeRequest
	(*RuntimeResponse)(nil), // 1: gachaMachine.runtime.RuntimeResponse
}
var file_gachaMachine_Websocket_gachaMachine_runtime_proto_depIdxs = []int32{
	0, // 0: gachaMachine.runtime.GachaMachineRuntimeService.GetPullResultWs:input_type -> gachaMachine.runtime.RuntimeRequest
	0, // 1: gachaMachine.runtime.GachaMachineRuntimeService.GetPlayerInfoWs:input_type -> gachaMachine.runtime.RuntimeRequest
	0, // 2: gachaMachine.runtime.GachaMachineRuntimeService.GetMachineInfoWs:input_type -> gachaMachine.runtime.RuntimeRequest
	1, // 3: gachaMachine.runtime.GachaMachineRuntimeService.GetPullResultWs:output_type -> gachaMachine.runtime.RuntimeResponse
	1, // 4: gachaMachine.runtime.GachaMachineRuntimeService.GetPlayerInfoWs:output_type -> gachaMachine.runtime.RuntimeResponse
	1, // 5: gachaMachine.runtime.GachaMachineRuntimeService.GetMachineInfoWs:output_type -> gachaMachine.runtime.RuntimeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gachaMachine_Websocket_gachaMachine_runtime_proto_init() }
func file_gachaMachine_Websocket_gachaMachine_runtime_proto_init() {
	if File_gachaMachine_Websocket_gachaMachine_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gachaMachine_Websocket_gachaMachine_runtime_proto_rawDesc), len(file_gachaMachine_Websocket_gachaMachine_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gachaMachine_Websocket_gachaMachine_runtime_proto_goTypes,
		DependencyIndexes: file_gachaMachine_Websocket_gachaMachine_runtime_proto_depIdxs,
		MessageInfos:      file_gachaMachine_Websocket_gachaMachine_runtime_proto_msgTypes,
	}.Build()
	File_gachaMachine_Websocket_gachaMachine_runtime_proto = out.File
	file_gachaMachine_Websocket_gachaMachine_runtime_proto_goTypes = nil
	file_gachaMachine_Websocket_gachaMachine_runtime_proto_depIdxs = nil
}
