syntax = "proto3";

package gachaMachine.runtime;

option go_package = "github.com/1nterdigital/game/pkg/protocol/gachaMachine_Websocket";


message RuntimeRequest {
    bytes payload = 1;
}

message RuntimeResponse {
    bytes payload = 1;
}

service GachaMachineRuntimeService {
    rpc GetPullResultWs (RuntimeRequest) returns (RuntimeResponse);
    rpc GetPlayerInfoWs (RuntimeRequest) returns (RuntimeResponse);
    rpc GetMachineInfoWs (RuntimeRequest) returns (RuntimeResponse);
    rpc GetPlayerInventoryWs (RuntimeRequest) returns (RuntimeResponse);
    rpc GetPlayerPullHistoryWs (RuntimeRequest) returns (RuntimeResponse);
}
