// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: clawMachine_Websocket/clawMachine_runtime.proto

package clawMachine_Websocket

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClawMachineRuntimeService_StartClawGameWs_FullMethodName        = "/clawMachine.runtime.ClawMachineRuntimeService/StartClawGameWs"
	ClawMachineRuntimeService_AddTouchedItemRecordWs_FullMethodName = "/clawMachine.runtime.ClawMachineRuntimeService/AddTouchedItemRecordWs"
	ClawMachineRuntimeService_GetPlayerInfoWs_FullMethodName        = "/clawMachine.runtime.ClawMachineRuntimeService/GetPlayerInfoWs"
	ClawMachineRuntimeService_GetMachineInfoWs_FullMethodName       = "/clawMachine.runtime.ClawMachineRuntimeService/GetMachineInfoWs"
)

// ClawMachineRuntimeServiceClient is the client API for ClawMachineRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClawMachineRuntimeServiceClient interface {
	StartClawGameWs(ctx context.Context, in *RuntimeRequest, opts ...grpc.CallOption) (*RuntimeResponse, error)
	AddTouchedItemRecordWs(ctx context.Context, in *RuntimeRequest, opts ...grpc.CallOption) (*RuntimeResponse, error)
	GetPlayerInfoWs(ctx context.Context, in *RuntimeRequest, opts ...grpc.CallOption) (*RuntimeResponse, error)
	GetMachineInfoWs(ctx context.Context, in *RuntimeRequest, opts ...grpc.CallOption) (*RuntimeResponse, error)
}

type clawMachineRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClawMachineRuntimeServiceClient(cc grpc.ClientConnInterface) ClawMachineRuntimeServiceClient {
	return &clawMachineRuntimeServiceClient{cc}
}

func (c *clawMachineRuntimeServiceClient) StartClawGameWs(ctx context.Context, in *RuntimeRequest, opts ...grpc.CallOption) (*RuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeResponse)
	err := c.cc.Invoke(ctx, ClawMachineRuntimeService_StartClawGameWs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawMachineRuntimeServiceClient) AddTouchedItemRecordWs(ctx context.Context, in *RuntimeRequest, opts ...grpc.CallOption) (*RuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeResponse)
	err := c.cc.Invoke(ctx, ClawMachineRuntimeService_AddTouchedItemRecordWs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawMachineRuntimeServiceClient) GetPlayerInfoWs(ctx context.Context, in *RuntimeRequest, opts ...grpc.CallOption) (*RuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeResponse)
	err := c.cc.Invoke(ctx, ClawMachineRuntimeService_GetPlayerInfoWs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawMachineRuntimeServiceClient) GetMachineInfoWs(ctx context.Context, in *RuntimeRequest, opts ...grpc.CallOption) (*RuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeResponse)
	err := c.cc.Invoke(ctx, ClawMachineRuntimeService_GetMachineInfoWs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClawMachineRuntimeServiceServer is the server API for ClawMachineRuntimeService service.
// All implementations must embed UnimplementedClawMachineRuntimeServiceServer
// for forward compatibility.
type ClawMachineRuntimeServiceServer interface {
	StartClawGameWs(context.Context, *RuntimeRequest) (*RuntimeResponse, error)
	AddTouchedItemRecordWs(context.Context, *RuntimeRequest) (*RuntimeResponse, error)
	GetPlayerInfoWs(context.Context, *RuntimeRequest) (*RuntimeResponse, error)
	GetMachineInfoWs(context.Context, *RuntimeRequest) (*RuntimeResponse, error)
	mustEmbedUnimplementedClawMachineRuntimeServiceServer()
}

// UnimplementedClawMachineRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClawMachineRuntimeServiceServer struct{}

func (UnimplementedClawMachineRuntimeServiceServer) StartClawGameWs(context.Context, *RuntimeRequest) (*RuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartClawGameWs not implemented")
}
func (UnimplementedClawMachineRuntimeServiceServer) AddTouchedItemRecordWs(context.Context, *RuntimeRequest) (*RuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTouchedItemRecordWs not implemented")
}
func (UnimplementedClawMachineRuntimeServiceServer) GetPlayerInfoWs(context.Context, *RuntimeRequest) (*RuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerInfoWs not implemented")
}
func (UnimplementedClawMachineRuntimeServiceServer) GetMachineInfoWs(context.Context, *RuntimeRequest) (*RuntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMachineInfoWs not implemented")
}
func (UnimplementedClawMachineRuntimeServiceServer) mustEmbedUnimplementedClawMachineRuntimeServiceServer() {
}
func (UnimplementedClawMachineRuntimeServiceServer) testEmbeddedByValue() {}

// UnsafeClawMachineRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClawMachineRuntimeServiceServer will
// result in compilation errors.
type UnsafeClawMachineRuntimeServiceServer interface {
	mustEmbedUnimplementedClawMachineRuntimeServiceServer()
}

func RegisterClawMachineRuntimeServiceServer(s grpc.ServiceRegistrar, srv ClawMachineRuntimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedClawMachineRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClawMachineRuntimeService_ServiceDesc, srv)
}

func _ClawMachineRuntimeService_StartClawGameWs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawMachineRuntimeServiceServer).StartClawGameWs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawMachineRuntimeService_StartClawGameWs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawMachineRuntimeServiceServer).StartClawGameWs(ctx, req.(*RuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClawMachineRuntimeService_AddTouchedItemRecordWs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawMachineRuntimeServiceServer).AddTouchedItemRecordWs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawMachineRuntimeService_AddTouchedItemRecordWs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawMachineRuntimeServiceServer).AddTouchedItemRecordWs(ctx, req.(*RuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClawMachineRuntimeService_GetPlayerInfoWs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawMachineRuntimeServiceServer).GetPlayerInfoWs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawMachineRuntimeService_GetPlayerInfoWs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawMachineRuntimeServiceServer).GetPlayerInfoWs(ctx, req.(*RuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClawMachineRuntimeService_GetMachineInfoWs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawMachineRuntimeServiceServer).GetMachineInfoWs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawMachineRuntimeService_GetMachineInfoWs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawMachineRuntimeServiceServer).GetMachineInfoWs(ctx, req.(*RuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClawMachineRuntimeService_ServiceDesc is the grpc.ServiceDesc for ClawMachineRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClawMachineRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawMachine.runtime.ClawMachineRuntimeService",
	HandlerType: (*ClawMachineRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartClawGameWs",
			Handler:    _ClawMachineRuntimeService_StartClawGameWs_Handler,
		},
		{
			MethodName: "AddTouchedItemRecordWs",
			Handler:    _ClawMachineRuntimeService_AddTouchedItemRecordWs_Handler,
		},
		{
			MethodName: "GetPlayerInfoWs",
			Handler:    _ClawMachineRuntimeService_GetPlayerInfoWs_Handler,
		},
		{
			MethodName: "GetMachineInfoWs",
			Handler:    _ClawMachineRuntimeService_GetMachineInfoWs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clawMachine_Websocket/clawMachine_runtime.proto",
}
