// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: player.proto

package player

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlayerServices_GetPlayerInfo_FullMethodName = "/player.PlayerServices/GetPlayerInfo"
)

// PlayerServicesClient is the client API for PlayerServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerServicesClient interface {
	GetPlayerInfo(ctx context.Context, in *GetPlayerInfoReq, opts ...grpc.CallOption) (*GetPlayerInfoResp, error)
}

type playerServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerServicesClient(cc grpc.ClientConnInterface) PlayerServicesClient {
	return &playerServicesClient{cc}
}

func (c *playerServicesClient) GetPlayerInfo(ctx context.Context, in *GetPlayerInfoReq, opts ...grpc.CallOption) (*GetPlayerInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerInfoResp)
	err := c.cc.Invoke(ctx, PlayerServices_GetPlayerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerServicesServer is the server API for PlayerServices service.
// All implementations must embed UnimplementedPlayerServicesServer
// for forward compatibility.
type PlayerServicesServer interface {
	GetPlayerInfo(context.Context, *GetPlayerInfoReq) (*GetPlayerInfoResp, error)
	mustEmbedUnimplementedPlayerServicesServer()
}

// UnimplementedPlayerServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlayerServicesServer struct{}

func (UnimplementedPlayerServicesServer) GetPlayerInfo(context.Context, *GetPlayerInfoReq) (*GetPlayerInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerInfo not implemented")
}
func (UnimplementedPlayerServicesServer) mustEmbedUnimplementedPlayerServicesServer() {}
func (UnimplementedPlayerServicesServer) testEmbeddedByValue()                        {}

// UnsafePlayerServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerServicesServer will
// result in compilation errors.
type UnsafePlayerServicesServer interface {
	mustEmbedUnimplementedPlayerServicesServer()
}

func RegisterPlayerServicesServer(s grpc.ServiceRegistrar, srv PlayerServicesServer) {
	// If the following call pancis, it indicates UnimplementedPlayerServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlayerServices_ServiceDesc, srv)
}

func _PlayerServices_GetPlayerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServicesServer).GetPlayerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerServices_GetPlayerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServicesServer).GetPlayerInfo(ctx, req.(*GetPlayerInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PlayerServices_ServiceDesc is the grpc.ServiceDesc for PlayerServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "player.PlayerServices",
	HandlerType: (*PlayerServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayerInfo",
			Handler:    _PlayerServices_GetPlayerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "player.proto",
}
