// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package whackAMole

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetLeaderboardResp struct {
	_tab flatbuffers.Table
}

func GetRootAsGetLeaderboardResp(buf []byte, offset flatbuffers.UOffsetT) *GetLeaderboardResp {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetLeaderboardResp{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetLeaderboardRespBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetLeaderboardResp(buf []byte, offset flatbuffers.UOffsetT) *GetLeaderboardResp {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetLeaderboardResp{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetLeaderboardRespBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetLeaderboardResp) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetLeaderboardResp) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetLeaderboardResp) TopPlayer(obj *LeaderboardPlayer, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *GetLeaderboardResp) TopPlayerLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GetLeaderboardResp) YourRank() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetLeaderboardResp) MutateYourRank(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *GetLeaderboardResp) YourScore() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetLeaderboardResp) MutateYourScore(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func GetLeaderboardRespStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func GetLeaderboardRespAddTopPlayer(builder *flatbuffers.Builder, topPlayer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(topPlayer), 0)
}
func GetLeaderboardRespStartTopPlayerVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GetLeaderboardRespAddYourRank(builder *flatbuffers.Builder, yourRank int32) {
	builder.PrependInt32Slot(1, yourRank, 0)
}
func GetLeaderboardRespAddYourScore(builder *flatbuffers.Builder, yourScore int64) {
	builder.PrependInt64Slot(2, yourScore, 0)
}
func GetLeaderboardRespEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
