// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package whackAMole

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LeaderboardPlayer struct {
	_tab flatbuffers.Table
}

func GetRootAsLeaderboardPlayer(buf []byte, offset flatbuffers.UOffsetT) *LeaderboardPlayer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LeaderboardPlayer{}
	x.Init(buf, n+offset)
	return x
}

func FinishLeaderboardPlayerBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLeaderboardPlayer(buf []byte, offset flatbuffers.UOffsetT) *LeaderboardPlayer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LeaderboardPlayer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLeaderboardPlayerBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LeaderboardPlayer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LeaderboardPlayer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LeaderboardPlayer) Rank() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LeaderboardPlayer) MutateRank(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *LeaderboardPlayer) PlayerId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LeaderboardPlayer) MutatePlayerId(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *LeaderboardPlayer) Username() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LeaderboardPlayer) Score() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LeaderboardPlayer) MutateScore(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func LeaderboardPlayerStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func LeaderboardPlayerAddRank(builder *flatbuffers.Builder, rank int32) {
	builder.PrependInt32Slot(0, rank, 0)
}
func LeaderboardPlayerAddPlayerId(builder *flatbuffers.Builder, playerId int64) {
	builder.PrependInt64Slot(1, playerId, 0)
}
func LeaderboardPlayerAddUsername(builder *flatbuffers.Builder, username flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(username), 0)
}
func LeaderboardPlayerAddScore(builder *flatbuffers.Builder, score int64) {
	builder.PrependInt64Slot(3, score, 0)
}
func LeaderboardPlayerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
