// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package whackAMole

import "strconv"

type MessageType int8

const (
	MessageTypeGetMoleWeightReq   MessageType = 0
	MessageTypeGetMoleWeightResp  MessageType = 1
	MessageTypeGetLeaderboardReq  MessageType = 2
	MessageTypeGetLeaderboardResp MessageType = 3
	MessageTypeErrorResp          MessageType = 100
)

var EnumNamesMessageType = map[MessageType]string{
	MessageTypeGetMoleWeightReq:   "GetMoleWeightReq",
	MessageTypeGetMoleWeightResp:  "GetMoleWeightResp",
	MessageTypeGetLeaderboardReq:  "GetLeaderboardReq",
	MessageTypeGetLeaderboardResp: "GetLeaderboardResp",
	MessageTypeErrorResp:          "ErrorResp",
}

var EnumValuesMessageType = map[string]MessageType{
	"GetMoleWeightReq":   MessageTypeGetMoleWeightReq,
	"GetMoleWeightResp":  MessageTypeGetMoleWeightResp,
	"GetLeaderboardReq":  MessageTypeGetLeaderboardReq,
	"GetLeaderboardResp": MessageTypeGetLeaderboardResp,
	"ErrorResp":          MessageTypeErrorResp,
}

func (v MessageType) String() string {
	if s, ok := EnumNamesMessageType[v]; ok {
		return s
	}
	return "MessageType(" + strconv.FormatInt(int64(v), 10) + ")"
}
