// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package whackAMole

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MoleWeight struct {
	_tab flatbuffers.Table
}

func GetRootAsMoleWeight(buf []byte, offset flatbuffers.UOffsetT) *MoleWeight {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MoleWeight{}
	x.Init(buf, n+offset)
	return x
}

func FinishMoleWeightBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMoleWeight(buf []byte, offset flatbuffers.UOffsetT) *MoleWeight {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MoleWeight{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMoleWeightBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MoleWeight) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MoleWeight) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MoleWeight) MoleType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MoleWeight) Weight() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MoleWeight) MutateWeight(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func MoleWeightStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MoleWeightAddMoleType(builder *flatbuffers.Builder, moleType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(moleType), 0)
}
func MoleWeightAddWeight(builder *flatbuffers.Builder, weight int32) {
	builder.PrependInt32Slot(1, weight, 0)
}
func MoleWeightEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
