// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: clawMachine/clawMachine.proto

package clawMachine

import (
	player "github.com/Richard-inter/game/pkg/protocol/player"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClawPlayer struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BasePlayer *player.Player         `protobuf:"bytes,1,opt,name=basePlayer,proto3" json:"basePlayer,omitempty"`
	// game specific attributes
	Coin          int64 `protobuf:"varint,2,opt,name=coin,proto3" json:"coin,omitempty"`
	Diamond       int64 `protobuf:"varint,3,opt,name=diamond,proto3" json:"diamond,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClawPlayer) Reset() {
	*x = ClawPlayer{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClawPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClawPlayer) ProtoMessage() {}

func (x *ClawPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClawPlayer.ProtoReflect.Descriptor instead.
func (*ClawPlayer) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{0}
}

func (x *ClawPlayer) GetBasePlayer() *player.Player {
	if x != nil {
		return x.BasePlayer
	}
	return nil
}

func (x *ClawPlayer) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *ClawPlayer) GetDiamond() int64 {
	if x != nil {
		return x.Diamond
	}
	return 0
}

type StartClawGameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	MachineID     int64                  `protobuf:"varint,2,opt,name=machineID,proto3" json:"machineID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartClawGameReq) Reset() {
	*x = StartClawGameReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartClawGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartClawGameReq) ProtoMessage() {}

func (x *StartClawGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartClawGameReq.ProtoReflect.Descriptor instead.
func (*StartClawGameReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{1}
}

func (x *StartClawGameReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *StartClawGameReq) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

type ClawResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemID        int64                  `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Catched       bool                   `protobuf:"varint,2,opt,name=catched,proto3" json:"catched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClawResult) Reset() {
	*x = ClawResult{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClawResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClawResult) ProtoMessage() {}

func (x *ClawResult) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClawResult.ProtoReflect.Descriptor instead.
func (*ClawResult) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{2}
}

func (x *ClawResult) GetItemID() int64 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *ClawResult) GetCatched() bool {
	if x != nil {
		return x.Catched
	}
	return false
}

type StartClawGameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameID        int64                  `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	Results       []*ClawResult          `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartClawGameResp) Reset() {
	*x = StartClawGameResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartClawGameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartClawGameResp) ProtoMessage() {}

func (x *StartClawGameResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartClawGameResp.ProtoReflect.Descriptor instead.
func (*StartClawGameResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{3}
}

func (x *StartClawGameResp) GetGameID() int64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *StartClawGameResp) GetResults() []*ClawResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetClawPlayerInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClawPlayerInfoReq) Reset() {
	*x = GetClawPlayerInfoReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClawPlayerInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClawPlayerInfoReq) ProtoMessage() {}

func (x *GetClawPlayerInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClawPlayerInfoReq.ProtoReflect.Descriptor instead.
func (*GetClawPlayerInfoReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{4}
}

func (x *GetClawPlayerInfoReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

type GetClawPlayerInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *ClawPlayer            `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClawPlayerInfoResp) Reset() {
	*x = GetClawPlayerInfoResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClawPlayerInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClawPlayerInfoResp) ProtoMessage() {}

func (x *GetClawPlayerInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClawPlayerInfoResp.ProtoReflect.Descriptor instead.
func (*GetClawPlayerInfoResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{5}
}

func (x *GetClawPlayerInfoResp) GetPlayer() *ClawPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

var File_clawMachine_clawMachine_proto protoreflect.FileDescriptor

const file_clawMachine_clawMachine_proto_rawDesc = "" +
	"\n" +
	"\x1dclawMachine/clawMachine.proto\x12\vclawMachine\x1a\x13player/player.proto\"j\n" +
	"\n" +
	"ClawPlayer\x12.\n" +
	"\n" +
	"basePlayer\x18\x01 \x01(\v2\x0e.player.PlayerR\n" +
	"basePlayer\x12\x12\n" +
	"\x04coin\x18\x02 \x01(\x03R\x04coin\x12\x18\n" +
	"\adiamond\x18\x03 \x01(\x03R\adiamond\"L\n" +
	"\x10StartClawGameReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\x12\x1c\n" +
	"\tmachineID\x18\x02 \x01(\x03R\tmachineID\">\n" +
	"\n" +
	"ClawResult\x12\x16\n" +
	"\x06itemID\x18\x01 \x01(\x03R\x06itemID\x12\x18\n" +
	"\acatched\x18\x02 \x01(\bR\acatched\"^\n" +
	"\x11StartClawGameResp\x12\x16\n" +
	"\x06gameID\x18\x01 \x01(\x03R\x06gameID\x121\n" +
	"\aresults\x18\x02 \x03(\v2\x17.clawMachine.ClawResultR\aresults\"2\n" +
	"\x14GetClawPlayerInfoReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\"H\n" +
	"\x15GetClawPlayerInfoResp\x12/\n" +
	"\x06player\x18\x01 \x01(\v2\x17.clawMachine.ClawPlayerR\x06player2\xc0\x01\n" +
	"\x12ClawMachineService\x12N\n" +
	"\rStartClawGame\x12\x1d.clawMachine.StartClawGameReq\x1a\x1e.clawMachine.StartClawGameResp\x12Z\n" +
	"\x11GetClawPlayerInfo\x12!.clawMachine.GetClawPlayerInfoReq\x1a\".clawMachine.GetClawPlayerInfoRespB8Z6github.com/Richard-inter/game/pkg/protocol/clawMachineb\x06proto3"

var (
	file_clawMachine_clawMachine_proto_rawDescOnce sync.Once
	file_clawMachine_clawMachine_proto_rawDescData []byte
)

func file_clawMachine_clawMachine_proto_rawDescGZIP() []byte {
	file_clawMachine_clawMachine_proto_rawDescOnce.Do(func() {
		file_clawMachine_clawMachine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clawMachine_clawMachine_proto_rawDesc), len(file_clawMachine_clawMachine_proto_rawDesc)))
	})
	return file_clawMachine_clawMachine_proto_rawDescData
}

var file_clawMachine_clawMachine_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_clawMachine_clawMachine_proto_goTypes = []any{
	(*ClawPlayer)(nil),            // 0: clawMachine.ClawPlayer
	(*StartClawGameReq)(nil),      // 1: clawMachine.StartClawGameReq
	(*ClawResult)(nil),            // 2: clawMachine.ClawResult
	(*StartClawGameResp)(nil),     // 3: clawMachine.StartClawGameResp
	(*GetClawPlayerInfoReq)(nil),  // 4: clawMachine.GetClawPlayerInfoReq
	(*GetClawPlayerInfoResp)(nil), // 5: clawMachine.GetClawPlayerInfoResp
	(*player.Player)(nil),         // 6: player.Player
}
var file_clawMachine_clawMachine_proto_depIdxs = []int32{
	6, // 0: clawMachine.ClawPlayer.basePlayer:type_name -> player.Player
	2, // 1: clawMachine.StartClawGameResp.results:type_name -> clawMachine.ClawResult
	0, // 2: clawMachine.GetClawPlayerInfoResp.player:type_name -> clawMachine.ClawPlayer
	1, // 3: clawMachine.ClawMachineService.StartClawGame:input_type -> clawMachine.StartClawGameReq
	4, // 4: clawMachine.ClawMachineService.GetClawPlayerInfo:input_type -> clawMachine.GetClawPlayerInfoReq
	3, // 5: clawMachine.ClawMachineService.StartClawGame:output_type -> clawMachine.StartClawGameResp
	5, // 6: clawMachine.ClawMachineService.GetClawPlayerInfo:output_type -> clawMachine.GetClawPlayerInfoResp
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_clawMachine_clawMachine_proto_init() }
func file_clawMachine_clawMachine_proto_init() {
	if File_clawMachine_clawMachine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clawMachine_clawMachine_proto_rawDesc), len(file_clawMachine_clawMachine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clawMachine_clawMachine_proto_goTypes,
		DependencyIndexes: file_clawMachine_clawMachine_proto_depIdxs,
		MessageInfos:      file_clawMachine_clawMachine_proto_msgTypes,
	}.Build()
	File_clawMachine_clawMachine_proto = out.File
	file_clawMachine_clawMachine_proto_goTypes = nil
	file_clawMachine_clawMachine_proto_depIdxs = nil
}
