// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: clawMachine/clawMachine.proto

package clawMachine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClawMachineService_StartClawGame_FullMethodName     = "/clawMachine.ClawMachineService/StartClawGame"
	ClawMachineService_GetClawPlayerInfo_FullMethodName = "/clawMachine.ClawMachineService/GetClawPlayerInfo"
)

// ClawMachineServiceClient is the client API for ClawMachineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClawMachineServiceClient interface {
	StartClawGame(ctx context.Context, in *StartClawGameReq, opts ...grpc.CallOption) (*StartClawGameResp, error)
	GetClawPlayerInfo(ctx context.Context, in *GetClawPlayerInfoReq, opts ...grpc.CallOption) (*GetClawPlayerInfoResp, error)
}

type clawMachineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClawMachineServiceClient(cc grpc.ClientConnInterface) ClawMachineServiceClient {
	return &clawMachineServiceClient{cc}
}

func (c *clawMachineServiceClient) StartClawGame(ctx context.Context, in *StartClawGameReq, opts ...grpc.CallOption) (*StartClawGameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartClawGameResp)
	err := c.cc.Invoke(ctx, ClawMachineService_StartClawGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clawMachineServiceClient) GetClawPlayerInfo(ctx context.Context, in *GetClawPlayerInfoReq, opts ...grpc.CallOption) (*GetClawPlayerInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClawPlayerInfoResp)
	err := c.cc.Invoke(ctx, ClawMachineService_GetClawPlayerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClawMachineServiceServer is the server API for ClawMachineService service.
// All implementations must embed UnimplementedClawMachineServiceServer
// for forward compatibility.
type ClawMachineServiceServer interface {
	StartClawGame(context.Context, *StartClawGameReq) (*StartClawGameResp, error)
	GetClawPlayerInfo(context.Context, *GetClawPlayerInfoReq) (*GetClawPlayerInfoResp, error)
	mustEmbedUnimplementedClawMachineServiceServer()
}

// UnimplementedClawMachineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClawMachineServiceServer struct{}

func (UnimplementedClawMachineServiceServer) StartClawGame(context.Context, *StartClawGameReq) (*StartClawGameResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartClawGame not implemented")
}
func (UnimplementedClawMachineServiceServer) GetClawPlayerInfo(context.Context, *GetClawPlayerInfoReq) (*GetClawPlayerInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClawPlayerInfo not implemented")
}
func (UnimplementedClawMachineServiceServer) mustEmbedUnimplementedClawMachineServiceServer() {}
func (UnimplementedClawMachineServiceServer) testEmbeddedByValue()                            {}

// UnsafeClawMachineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClawMachineServiceServer will
// result in compilation errors.
type UnsafeClawMachineServiceServer interface {
	mustEmbedUnimplementedClawMachineServiceServer()
}

func RegisterClawMachineServiceServer(s grpc.ServiceRegistrar, srv ClawMachineServiceServer) {
	// If the following call pancis, it indicates UnimplementedClawMachineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClawMachineService_ServiceDesc, srv)
}

func _ClawMachineService_StartClawGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartClawGameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawMachineServiceServer).StartClawGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawMachineService_StartClawGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawMachineServiceServer).StartClawGame(ctx, req.(*StartClawGameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClawMachineService_GetClawPlayerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClawPlayerInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClawMachineServiceServer).GetClawPlayerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClawMachineService_GetClawPlayerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClawMachineServiceServer).GetClawPlayerInfo(ctx, req.(*GetClawPlayerInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ClawMachineService_ServiceDesc is the grpc.ServiceDesc for ClawMachineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClawMachineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clawMachine.ClawMachineService",
	HandlerType: (*ClawMachineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartClawGame",
			Handler:    _ClawMachineService_StartClawGame_Handler,
		},
		{
			MethodName: "GetClawPlayerInfo",
			Handler:    _ClawMachineService_GetClawPlayerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clawMachine/clawMachine.proto",
}
