// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: clawMachine/clawMachine.proto

package clawMachine

import (
	player "github.com/Richard-inter/game/pkg/protocol/player"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ItemID          int64                  `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rarity          string                 `protobuf:"bytes,3,opt,name=rarity,proto3" json:"rarity,omitempty"`
	SpawnPercentage float64                `protobuf:"fixed64,4,opt,name=spawnPercentage,proto3" json:"spawnPercentage,omitempty"`
	CatchPercentage float64                `protobuf:"fixed64,5,opt,name=catchPercentage,proto3" json:"catchPercentage,omitempty"`
	MaxItemSpawned  int64                  `protobuf:"varint,6,opt,name=maxItemSpawned,proto3" json:"maxItemSpawned,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetItemID() int64 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *Item) GetSpawnPercentage() float64 {
	if x != nil {
		return x.SpawnPercentage
	}
	return 0
}

func (x *Item) GetCatchPercentage() float64 {
	if x != nil {
		return x.CatchPercentage
	}
	return 0
}

func (x *Item) GetMaxItemSpawned() int64 {
	if x != nil {
		return x.MaxItemSpawned
	}
	return 0
}

type ClawMachine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineID     int64                  `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Items         []*Item                `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	MaxItem       int32                  `protobuf:"varint,5,opt,name=maxItem,proto3" json:"maxItem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClawMachine) Reset() {
	*x = ClawMachine{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClawMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClawMachine) ProtoMessage() {}

func (x *ClawMachine) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClawMachine.ProtoReflect.Descriptor instead.
func (*ClawMachine) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{1}
}

func (x *ClawMachine) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

func (x *ClawMachine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClawMachine) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ClawMachine) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ClawMachine) GetMaxItem() int32 {
	if x != nil {
		return x.MaxItem
	}
	return 0
}

type ClawPlayer struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BasePlayer *player.Player         `protobuf:"bytes,1,opt,name=basePlayer,proto3" json:"basePlayer,omitempty"`
	// game specific attributes
	Coin          int64 `protobuf:"varint,2,opt,name=coin,proto3" json:"coin,omitempty"`
	Diamond       int64 `protobuf:"varint,3,opt,name=diamond,proto3" json:"diamond,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClawPlayer) Reset() {
	*x = ClawPlayer{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClawPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClawPlayer) ProtoMessage() {}

func (x *ClawPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClawPlayer.ProtoReflect.Descriptor instead.
func (*ClawPlayer) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{2}
}

func (x *ClawPlayer) GetBasePlayer() *player.Player {
	if x != nil {
		return x.BasePlayer
	}
	return nil
}

func (x *ClawPlayer) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *ClawPlayer) GetDiamond() int64 {
	if x != nil {
		return x.Diamond
	}
	return 0
}

type Items struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemID        int64                  `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Items) Reset() {
	*x = Items{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{3}
}

func (x *Items) GetItemID() int64 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

type CreateClawMachineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Items         []*Items               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	MaxItem       int32                  `protobuf:"varint,4,opt,name=maxItem,proto3" json:"maxItem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClawMachineReq) Reset() {
	*x = CreateClawMachineReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClawMachineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClawMachineReq) ProtoMessage() {}

func (x *CreateClawMachineReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClawMachineReq.ProtoReflect.Descriptor instead.
func (*CreateClawMachineReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{4}
}

func (x *CreateClawMachineReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClawMachineReq) GetItems() []*Items {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateClawMachineReq) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateClawMachineReq) GetMaxItem() int32 {
	if x != nil {
		return x.MaxItem
	}
	return 0
}

type CreateClawMachineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *ClawMachine           `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClawMachineResp) Reset() {
	*x = CreateClawMachineResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClawMachineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClawMachineResp) ProtoMessage() {}

func (x *CreateClawMachineResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClawMachineResp.ProtoReflect.Descriptor instead.
func (*CreateClawMachineResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{5}
}

func (x *CreateClawMachineResp) GetMachine() *ClawMachine {
	if x != nil {
		return x.Machine
	}
	return nil
}

type StartClawGameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	MachineID     int64                  `protobuf:"varint,2,opt,name=machineID,proto3" json:"machineID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartClawGameReq) Reset() {
	*x = StartClawGameReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartClawGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartClawGameReq) ProtoMessage() {}

func (x *StartClawGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartClawGameReq.ProtoReflect.Descriptor instead.
func (*StartClawGameReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{6}
}

func (x *StartClawGameReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *StartClawGameReq) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

type ClawResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemID        int64                  `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Catched       *bool                  `protobuf:"varint,2,opt,name=catched,proto3,oneof" json:"catched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClawResult) Reset() {
	*x = ClawResult{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClawResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClawResult) ProtoMessage() {}

func (x *ClawResult) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClawResult.ProtoReflect.Descriptor instead.
func (*ClawResult) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{7}
}

func (x *ClawResult) GetItemID() int64 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *ClawResult) GetCatched() bool {
	if x != nil && x.Catched != nil {
		return *x.Catched
	}
	return false
}

type StartClawGameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameID        int64                  `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	Results       []*ClawResult          `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartClawGameResp) Reset() {
	*x = StartClawGameResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartClawGameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartClawGameResp) ProtoMessage() {}

func (x *StartClawGameResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartClawGameResp.ProtoReflect.Descriptor instead.
func (*StartClawGameResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{8}
}

func (x *StartClawGameResp) GetGameID() int64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *StartClawGameResp) GetResults() []*ClawResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetClawPlayerInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClawPlayerInfoReq) Reset() {
	*x = GetClawPlayerInfoReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClawPlayerInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClawPlayerInfoReq) ProtoMessage() {}

func (x *GetClawPlayerInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClawPlayerInfoReq.ProtoReflect.Descriptor instead.
func (*GetClawPlayerInfoReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{9}
}

func (x *GetClawPlayerInfoReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

type GetClawPlayerInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *ClawPlayer            `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClawPlayerInfoResp) Reset() {
	*x = GetClawPlayerInfoResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClawPlayerInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClawPlayerInfoResp) ProtoMessage() {}

func (x *GetClawPlayerInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClawPlayerInfoResp.ProtoReflect.Descriptor instead.
func (*GetClawPlayerInfoResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{10}
}

func (x *GetClawPlayerInfoResp) GetPlayer() *ClawPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

type GetClawMachineInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineID     int64                  `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClawMachineInfoReq) Reset() {
	*x = GetClawMachineInfoReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClawMachineInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClawMachineInfoReq) ProtoMessage() {}

func (x *GetClawMachineInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClawMachineInfoReq.ProtoReflect.Descriptor instead.
func (*GetClawMachineInfoReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{11}
}

func (x *GetClawMachineInfoReq) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

type GetClawMachineInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       []*ClawMachine         `protobuf:"bytes,1,rep,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClawMachineInfoResp) Reset() {
	*x = GetClawMachineInfoResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClawMachineInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClawMachineInfoResp) ProtoMessage() {}

func (x *GetClawMachineInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClawMachineInfoResp.ProtoReflect.Descriptor instead.
func (*GetClawMachineInfoResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{12}
}

func (x *GetClawMachineInfoResp) GetMachine() []*ClawMachine {
	if x != nil {
		return x.Machine
	}
	return nil
}

type CreateItemReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rarity          string                 `protobuf:"bytes,2,opt,name=rarity,proto3" json:"rarity,omitempty"`
	SpawnPercentage float64                `protobuf:"fixed64,3,opt,name=spawnPercentage,proto3" json:"spawnPercentage,omitempty"`
	CatchPercentage float64                `protobuf:"fixed64,4,opt,name=catchPercentage,proto3" json:"catchPercentage,omitempty"`
	MaxItemSpawned  int64                  `protobuf:"varint,5,opt,name=maxItemSpawned,proto3" json:"maxItemSpawned,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateItemReq) Reset() {
	*x = CreateItemReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemReq) ProtoMessage() {}

func (x *CreateItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemReq.ProtoReflect.Descriptor instead.
func (*CreateItemReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{13}
}

func (x *CreateItemReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateItemReq) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *CreateItemReq) GetSpawnPercentage() float64 {
	if x != nil {
		return x.SpawnPercentage
	}
	return 0
}

func (x *CreateItemReq) GetCatchPercentage() float64 {
	if x != nil {
		return x.CatchPercentage
	}
	return 0
}

func (x *CreateItemReq) GetMaxItemSpawned() int64 {
	if x != nil {
		return x.MaxItemSpawned
	}
	return 0
}

type CreateClawItemsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClawItems     []*CreateItemReq       `protobuf:"bytes,1,rep,name=clawItems,proto3" json:"clawItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClawItemsReq) Reset() {
	*x = CreateClawItemsReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClawItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClawItemsReq) ProtoMessage() {}

func (x *CreateClawItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClawItemsReq.ProtoReflect.Descriptor instead.
func (*CreateClawItemsReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{14}
}

func (x *CreateClawItemsReq) GetClawItems() []*CreateItemReq {
	if x != nil {
		return x.ClawItems
	}
	return nil
}

type CreateClawItemsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClawItems     []*Item                `protobuf:"bytes,2,rep,name=clawItems,proto3" json:"clawItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClawItemsResp) Reset() {
	*x = CreateClawItemsResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClawItemsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClawItemsResp) ProtoMessage() {}

func (x *CreateClawItemsResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClawItemsResp.ProtoReflect.Descriptor instead.
func (*CreateClawItemsResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{15}
}

func (x *CreateClawItemsResp) GetClawItems() []*Item {
	if x != nil {
		return x.ClawItems
	}
	return nil
}

type CreateClawPlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *ClawPlayer            `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClawPlayerReq) Reset() {
	*x = CreateClawPlayerReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClawPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClawPlayerReq) ProtoMessage() {}

func (x *CreateClawPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClawPlayerReq.ProtoReflect.Descriptor instead.
func (*CreateClawPlayerReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{16}
}

func (x *CreateClawPlayerReq) GetPlayer() *ClawPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

type CreateClawPlayerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *ClawPlayer            `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClawPlayerResp) Reset() {
	*x = CreateClawPlayerResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClawPlayerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClawPlayerResp) ProtoMessage() {}

func (x *CreateClawPlayerResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClawPlayerResp.ProtoReflect.Descriptor instead.
func (*CreateClawPlayerResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{17}
}

func (x *CreateClawPlayerResp) GetPlayer() *ClawPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

type AdjustPlayerCoinReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustPlayerCoinReq) Reset() {
	*x = AdjustPlayerCoinReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustPlayerCoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustPlayerCoinReq) ProtoMessage() {}

func (x *AdjustPlayerCoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustPlayerCoinReq.ProtoReflect.Descriptor instead.
func (*AdjustPlayerCoinReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{18}
}

func (x *AdjustPlayerCoinReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *AdjustPlayerCoinReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AdjustPlayerCoinReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type AdjustPlayerCoinResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerID       int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	AdjustedAmount int64                  `protobuf:"varint,2,opt,name=adjustedAmount,proto3" json:"adjustedAmount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdjustPlayerCoinResp) Reset() {
	*x = AdjustPlayerCoinResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustPlayerCoinResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustPlayerCoinResp) ProtoMessage() {}

func (x *AdjustPlayerCoinResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustPlayerCoinResp.ProtoReflect.Descriptor instead.
func (*AdjustPlayerCoinResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{19}
}

func (x *AdjustPlayerCoinResp) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *AdjustPlayerCoinResp) GetAdjustedAmount() int64 {
	if x != nil {
		return x.AdjustedAmount
	}
	return 0
}

type AdjustPlayerDiamondReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustPlayerDiamondReq) Reset() {
	*x = AdjustPlayerDiamondReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustPlayerDiamondReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustPlayerDiamondReq) ProtoMessage() {}

func (x *AdjustPlayerDiamondReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustPlayerDiamondReq.ProtoReflect.Descriptor instead.
func (*AdjustPlayerDiamondReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{20}
}

func (x *AdjustPlayerDiamondReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *AdjustPlayerDiamondReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AdjustPlayerDiamondReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type AdjustPlayerDiamondResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerID       int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	AdjustedAmount int64                  `protobuf:"varint,2,opt,name=adjustedAmount,proto3" json:"adjustedAmount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdjustPlayerDiamondResp) Reset() {
	*x = AdjustPlayerDiamondResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustPlayerDiamondResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustPlayerDiamondResp) ProtoMessage() {}

func (x *AdjustPlayerDiamondResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustPlayerDiamondResp.ProtoReflect.Descriptor instead.
func (*AdjustPlayerDiamondResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{21}
}

func (x *AdjustPlayerDiamondResp) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *AdjustPlayerDiamondResp) GetAdjustedAmount() int64 {
	if x != nil {
		return x.AdjustedAmount
	}
	return 0
}

type AddTouchedItemRecordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameID        int64                  `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	ItemID        int64                  `protobuf:"varint,2,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Catched       *bool                  `protobuf:"varint,3,opt,name=catched,proto3,oneof" json:"catched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTouchedItemRecordReq) Reset() {
	*x = AddTouchedItemRecordReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTouchedItemRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTouchedItemRecordReq) ProtoMessage() {}

func (x *AddTouchedItemRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTouchedItemRecordReq.ProtoReflect.Descriptor instead.
func (*AddTouchedItemRecordReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{22}
}

func (x *AddTouchedItemRecordReq) GetGameID() int64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *AddTouchedItemRecordReq) GetItemID() int64 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *AddTouchedItemRecordReq) GetCatched() bool {
	if x != nil && x.Catched != nil {
		return *x.Catched
	}
	return false
}

type AddTouchedItemRecordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameID        int64                  `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	ItemID        int64                  `protobuf:"varint,2,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Catched       *bool                  `protobuf:"varint,3,opt,name=catched,proto3,oneof" json:"catched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTouchedItemRecordResp) Reset() {
	*x = AddTouchedItemRecordResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTouchedItemRecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTouchedItemRecordResp) ProtoMessage() {}

func (x *AddTouchedItemRecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTouchedItemRecordResp.ProtoReflect.Descriptor instead.
func (*AddTouchedItemRecordResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{23}
}

func (x *AddTouchedItemRecordResp) GetGameID() int64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *AddTouchedItemRecordResp) GetItemID() int64 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *AddTouchedItemRecordResp) GetCatched() bool {
	if x != nil && x.Catched != nil {
		return *x.Catched
	}
	return false
}

type DeleteClawPlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClawPlayerReq) Reset() {
	*x = DeleteClawPlayerReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClawPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClawPlayerReq) ProtoMessage() {}

func (x *DeleteClawPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClawPlayerReq.ProtoReflect.Descriptor instead.
func (*DeleteClawPlayerReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteClawPlayerReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

type DeleteClawPlayerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClawPlayerResp) Reset() {
	*x = DeleteClawPlayerResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClawPlayerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClawPlayerResp) ProtoMessage() {}

func (x *DeleteClawPlayerResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClawPlayerResp.ProtoReflect.Descriptor instead.
func (*DeleteClawPlayerResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteClawPlayerResp) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *DeleteClawPlayerResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetGameHistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameHistoryReq) Reset() {
	*x = GetGameHistoryReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameHistoryReq) ProtoMessage() {}

func (x *GetGameHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameHistoryReq.ProtoReflect.Descriptor instead.
func (*GetGameHistoryReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{26}
}

func (x *GetGameHistoryReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

type ClawMachineGameRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameID        int64                  `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	ClawMachineID int64                  `protobuf:"varint,2,opt,name=clawMachineID,proto3" json:"clawMachineID,omitempty"`
	PlayerID      int64                  `protobuf:"varint,3,opt,name=playerID,proto3" json:"playerID,omitempty"`
	TouchedItemID int64                  `protobuf:"varint,4,opt,name=touchedItemID,proto3" json:"touchedItemID,omitempty"`
	Catched       bool                   `protobuf:"varint,5,opt,name=catched,proto3" json:"catched,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClawMachineGameRecord) Reset() {
	*x = ClawMachineGameRecord{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClawMachineGameRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClawMachineGameRecord) ProtoMessage() {}

func (x *ClawMachineGameRecord) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClawMachineGameRecord.ProtoReflect.Descriptor instead.
func (*ClawMachineGameRecord) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{27}
}

func (x *ClawMachineGameRecord) GetGameID() int64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *ClawMachineGameRecord) GetClawMachineID() int64 {
	if x != nil {
		return x.ClawMachineID
	}
	return 0
}

func (x *ClawMachineGameRecord) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *ClawMachineGameRecord) GetTouchedItemID() int64 {
	if x != nil {
		return x.TouchedItemID
	}
	return 0
}

func (x *ClawMachineGameRecord) GetCatched() bool {
	if x != nil {
		return x.Catched
	}
	return false
}

func (x *ClawMachineGameRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetGameHistoryResp struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	GameRecords   []*ClawMachineGameRecord `protobuf:"bytes,1,rep,name=gameRecords,proto3" json:"gameRecords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameHistoryResp) Reset() {
	*x = GetGameHistoryResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameHistoryResp) ProtoMessage() {}

func (x *GetGameHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameHistoryResp.ProtoReflect.Descriptor instead.
func (*GetGameHistoryResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{28}
}

func (x *GetGameHistoryResp) GetGameRecords() []*ClawMachineGameRecord {
	if x != nil {
		return x.GameRecords
	}
	return nil
}

type UpdateClawMachineItemsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineID     int64                  `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	Items         []*Items               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClawMachineItemsReq) Reset() {
	*x = UpdateClawMachineItemsReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClawMachineItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClawMachineItemsReq) ProtoMessage() {}

func (x *UpdateClawMachineItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClawMachineItemsReq.ProtoReflect.Descriptor instead.
func (*UpdateClawMachineItemsReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateClawMachineItemsReq) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

func (x *UpdateClawMachineItemsReq) GetItems() []*Items {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateClawMachineItemsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineID     int64                  `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClawMachineItemsResp) Reset() {
	*x = UpdateClawMachineItemsResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClawMachineItemsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClawMachineItemsResp) ProtoMessage() {}

func (x *UpdateClawMachineItemsResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClawMachineItemsResp.ProtoReflect.Descriptor instead.
func (*UpdateClawMachineItemsResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateClawMachineItemsResp) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

func (x *UpdateClawMachineItemsResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteClawMachineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineID     int64                  `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClawMachineReq) Reset() {
	*x = DeleteClawMachineReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClawMachineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClawMachineReq) ProtoMessage() {}

func (x *DeleteClawMachineReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClawMachineReq.ProtoReflect.Descriptor instead.
func (*DeleteClawMachineReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteClawMachineReq) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

type DeleteClawMachineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineID     int64                  `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClawMachineResp) Reset() {
	*x = DeleteClawMachineResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClawMachineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClawMachineResp) ProtoMessage() {}

func (x *DeleteClawMachineResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClawMachineResp.ProtoReflect.Descriptor instead.
func (*DeleteClawMachineResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteClawMachineResp) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

func (x *DeleteClawMachineResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteClawItemsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIDs       []int64                `protobuf:"varint,1,rep,packed,name=itemIDs,proto3" json:"itemIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClawItemsReq) Reset() {
	*x = DeleteClawItemsReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClawItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClawItemsReq) ProtoMessage() {}

func (x *DeleteClawItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClawItemsReq.ProtoReflect.Descriptor instead.
func (*DeleteClawItemsReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{33}
}

func (x *DeleteClawItemsReq) GetItemIDs() []int64 {
	if x != nil {
		return x.ItemIDs
	}
	return nil
}

type DeleteClawItemsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIDs       []int64                `protobuf:"varint,1,rep,packed,name=itemIDs,proto3" json:"itemIDs,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClawItemsResp) Reset() {
	*x = DeleteClawItemsResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClawItemsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClawItemsResp) ProtoMessage() {}

func (x *DeleteClawItemsResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClawItemsResp.ProtoReflect.Descriptor instead.
func (*DeleteClawItemsResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteClawItemsResp) GetItemIDs() []int64 {
	if x != nil {
		return x.ItemIDs
	}
	return nil
}

func (x *DeleteClawItemsResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateClawMachineTargetRTPReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineID     int64                  `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	TargetRTP     float64                `protobuf:"fixed64,2,opt,name=targetRTP,proto3" json:"targetRTP,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClawMachineTargetRTPReq) Reset() {
	*x = UpdateClawMachineTargetRTPReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClawMachineTargetRTPReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClawMachineTargetRTPReq) ProtoMessage() {}

func (x *UpdateClawMachineTargetRTPReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClawMachineTargetRTPReq.ProtoReflect.Descriptor instead.
func (*UpdateClawMachineTargetRTPReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{35}
}

func (x *UpdateClawMachineTargetRTPReq) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

func (x *UpdateClawMachineTargetRTPReq) GetTargetRTP() float64 {
	if x != nil {
		return x.TargetRTP
	}
	return 0
}

type UpdateClawMachineTargetRTPResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineID     int64                  `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClawMachineTargetRTPResp) Reset() {
	*x = UpdateClawMachineTargetRTPResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClawMachineTargetRTPResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClawMachineTargetRTPResp) ProtoMessage() {}

func (x *UpdateClawMachineTargetRTPResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClawMachineTargetRTPResp.ProtoReflect.Descriptor instead.
func (*UpdateClawMachineTargetRTPResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{36}
}

func (x *UpdateClawMachineTargetRTPResp) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

func (x *UpdateClawMachineTargetRTPResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_clawMachine_clawMachine_proto protoreflect.FileDescriptor

const file_clawMachine_clawMachine_proto_rawDesc = "" +
	"\n" +
	"\x1dclawMachine/clawMachine.proto\x12\vclawMachine\x1a\x13player/player.proto\"\xc6\x01\n" +
	"\x04Item\x12\x16\n" +
	"\x06itemID\x18\x01 \x01(\x03R\x06itemID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06rarity\x18\x03 \x01(\tR\x06rarity\x12(\n" +
	"\x0fspawnPercentage\x18\x04 \x01(\x01R\x0fspawnPercentage\x12(\n" +
	"\x0fcatchPercentage\x18\x05 \x01(\x01R\x0fcatchPercentage\x12&\n" +
	"\x0emaxItemSpawned\x18\x06 \x01(\x03R\x0emaxItemSpawned\"\x98\x01\n" +
	"\vClawMachine\x12\x1c\n" +
	"\tmachineID\x18\x01 \x01(\x03R\tmachineID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x05items\x18\x03 \x03(\v2\x11.clawMachine.ItemR\x05items\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x18\n" +
	"\amaxItem\x18\x05 \x01(\x05R\amaxItem\"j\n" +
	"\n" +
	"ClawPlayer\x12.\n" +
	"\n" +
	"basePlayer\x18\x01 \x01(\v2\x0e.player.PlayerR\n" +
	"basePlayer\x12\x12\n" +
	"\x04coin\x18\x02 \x01(\x03R\x04coin\x12\x18\n" +
	"\adiamond\x18\x03 \x01(\x03R\adiamond\"\x1f\n" +
	"\x05Items\x12\x16\n" +
	"\x06itemID\x18\x01 \x01(\x03R\x06itemID\"\x84\x01\n" +
	"\x14CreateClawMachineReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.clawMachine.ItemsR\x05items\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x18\n" +
	"\amaxItem\x18\x04 \x01(\x05R\amaxItem\"K\n" +
	"\x15CreateClawMachineResp\x122\n" +
	"\amachine\x18\x01 \x01(\v2\x18.clawMachine.ClawMachineR\amachine\"L\n" +
	"\x10StartClawGameReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\x12\x1c\n" +
	"\tmachineID\x18\x02 \x01(\x03R\tmachineID\"O\n" +
	"\n" +
	"ClawResult\x12\x16\n" +
	"\x06itemID\x18\x01 \x01(\x03R\x06itemID\x12\x1d\n" +
	"\acatched\x18\x02 \x01(\bH\x00R\acatched\x88\x01\x01B\n" +
	"\n" +
	"\b_catched\"^\n" +
	"\x11StartClawGameResp\x12\x16\n" +
	"\x06gameID\x18\x01 \x01(\x03R\x06gameID\x121\n" +
	"\aresults\x18\x02 \x03(\v2\x17.clawMachine.ClawResultR\aresults\"2\n" +
	"\x14GetClawPlayerInfoReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\"H\n" +
	"\x15GetClawPlayerInfoResp\x12/\n" +
	"\x06player\x18\x01 \x01(\v2\x17.clawMachine.ClawPlayerR\x06player\"5\n" +
	"\x15GetClawMachineInfoReq\x12\x1c\n" +
	"\tmachineID\x18\x01 \x01(\x03R\tmachineID\"L\n" +
	"\x16GetClawMachineInfoResp\x122\n" +
	"\amachine\x18\x01 \x03(\v2\x18.clawMachine.ClawMachineR\amachine\"\xb7\x01\n" +
	"\rCreateItemReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06rarity\x18\x02 \x01(\tR\x06rarity\x12(\n" +
	"\x0fspawnPercentage\x18\x03 \x01(\x01R\x0fspawnPercentage\x12(\n" +
	"\x0fcatchPercentage\x18\x04 \x01(\x01R\x0fcatchPercentage\x12&\n" +
	"\x0emaxItemSpawned\x18\x05 \x01(\x03R\x0emaxItemSpawned\"N\n" +
	"\x12CreateClawItemsReq\x128\n" +
	"\tclawItems\x18\x01 \x03(\v2\x1a.clawMachine.CreateItemReqR\tclawItems\"F\n" +
	"\x13CreateClawItemsResp\x12/\n" +
	"\tclawItems\x18\x02 \x03(\v2\x11.clawMachine.ItemR\tclawItems\"F\n" +
	"\x13CreateClawPlayerReq\x12/\n" +
	"\x06player\x18\x01 \x01(\v2\x17.clawMachine.ClawPlayerR\x06player\"G\n" +
	"\x14CreateClawPlayerResp\x12/\n" +
	"\x06player\x18\x02 \x01(\v2\x17.clawMachine.ClawPlayerR\x06player\"]\n" +
	"\x13AdjustPlayerCoinReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"Z\n" +
	"\x14AdjustPlayerCoinResp\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\x12&\n" +
	"\x0eadjustedAmount\x18\x02 \x01(\x03R\x0eadjustedAmount\"`\n" +
	"\x16AdjustPlayerDiamondReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"]\n" +
	"\x17AdjustPlayerDiamondResp\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\x12&\n" +
	"\x0eadjustedAmount\x18\x02 \x01(\x03R\x0eadjustedAmount\"t\n" +
	"\x17AddTouchedItemRecordReq\x12\x16\n" +
	"\x06gameID\x18\x01 \x01(\x03R\x06gameID\x12\x16\n" +
	"\x06itemID\x18\x02 \x01(\x03R\x06itemID\x12\x1d\n" +
	"\acatched\x18\x03 \x01(\bH\x00R\acatched\x88\x01\x01B\n" +
	"\n" +
	"\b_catched\"u\n" +
	"\x18AddTouchedItemRecordResp\x12\x16\n" +
	"\x06gameID\x18\x01 \x01(\x03R\x06gameID\x12\x16\n" +
	"\x06itemID\x18\x02 \x01(\x03R\x06itemID\x12\x1d\n" +
	"\acatched\x18\x03 \x01(\bH\x00R\acatched\x88\x01\x01B\n" +
	"\n" +
	"\b_catched\"1\n" +
	"\x13DeleteClawPlayerReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\"L\n" +
	"\x14DeleteClawPlayerResp\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"/\n" +
	"\x11GetGameHistoryReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\"\xcf\x01\n" +
	"\x15ClawMachineGameRecord\x12\x16\n" +
	"\x06gameID\x18\x01 \x01(\x03R\x06gameID\x12$\n" +
	"\rclawMachineID\x18\x02 \x01(\x03R\rclawMachineID\x12\x1a\n" +
	"\bplayerID\x18\x03 \x01(\x03R\bplayerID\x12$\n" +
	"\rtouchedItemID\x18\x04 \x01(\x03R\rtouchedItemID\x12\x18\n" +
	"\acatched\x18\x05 \x01(\bR\acatched\x12\x1c\n" +
	"\tcreatedAt\x18\x06 \x01(\tR\tcreatedAt\"Z\n" +
	"\x12GetGameHistoryResp\x12D\n" +
	"\vgameRecords\x18\x01 \x03(\v2\".clawMachine.ClawMachineGameRecordR\vgameRecords\"c\n" +
	"\x19UpdateClawMachineItemsReq\x12\x1c\n" +
	"\tmachineID\x18\x01 \x01(\x03R\tmachineID\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.clawMachine.ItemsR\x05items\"T\n" +
	"\x1aUpdateClawMachineItemsResp\x12\x1c\n" +
	"\tmachineID\x18\x01 \x01(\x03R\tmachineID\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"4\n" +
	"\x14DeleteClawMachineReq\x12\x1c\n" +
	"\tmachineID\x18\x01 \x01(\x03R\tmachineID\"O\n" +
	"\x15DeleteClawMachineResp\x12\x1c\n" +
	"\tmachineID\x18\x01 \x01(\x03R\tmachineID\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\".\n" +
	"\x12DeleteClawItemsReq\x12\x18\n" +
	"\aitemIDs\x18\x01 \x03(\x03R\aitemIDs\"I\n" +
	"\x13DeleteClawItemsResp\x12\x18\n" +
	"\aitemIDs\x18\x01 \x03(\x03R\aitemIDs\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"[\n" +
	"\x1dUpdateClawMachineTargetRTPReq\x12\x1c\n" +
	"\tmachineID\x18\x01 \x01(\x03R\tmachineID\x12\x1c\n" +
	"\ttargetRTP\x18\x02 \x01(\x01R\ttargetRTP\"X\n" +
	"\x1eUpdateClawMachineTargetRTPResp\x12\x1c\n" +
	"\tmachineID\x18\x01 \x01(\x03R\tmachineID\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\x8a\v\n" +
	"\x12ClawMachineService\x12W\n" +
	"\x10CreateClawPlayer\x12 .clawMachine.CreateClawPlayerReq\x1a!.clawMachine.CreateClawPlayerResp\x12Z\n" +
	"\x11GetClawPlayerInfo\x12!.clawMachine.GetClawPlayerInfoReq\x1a\".clawMachine.GetClawPlayerInfoResp\x12W\n" +
	"\x10DeleteClawPlayer\x12 .clawMachine.DeleteClawPlayerReq\x1a!.clawMachine.DeleteClawPlayerResp\x12W\n" +
	"\x10AdjustPlayerCoin\x12 .clawMachine.AdjustPlayerCoinReq\x1a!.clawMachine.AdjustPlayerCoinResp\x12`\n" +
	"\x13AdjustPlayerDiamond\x12#.clawMachine.AdjustPlayerDiamondReq\x1a$.clawMachine.AdjustPlayerDiamondResp\x12Q\n" +
	"\x0eGetGameHistory\x12\x1e.clawMachine.GetGameHistoryReq\x1a\x1f.clawMachine.GetGameHistoryResp\x12Z\n" +
	"\x11CreateClawMachine\x12!.clawMachine.CreateClawMachineReq\x1a\".clawMachine.CreateClawMachineResp\x12]\n" +
	"\x12GetClawMachineInfo\x12\".clawMachine.GetClawMachineInfoReq\x1a#.clawMachine.GetClawMachineInfoResp\x12i\n" +
	"\x16UpdateClawMachineItems\x12&.clawMachine.UpdateClawMachineItemsReq\x1a'.clawMachine.UpdateClawMachineItemsResp\x12Z\n" +
	"\x11DeleteClawMachine\x12!.clawMachine.DeleteClawMachineReq\x1a\".clawMachine.DeleteClawMachineResp\x12N\n" +
	"\rStartClawGame\x12\x1d.clawMachine.StartClawGameReq\x1a\x1e.clawMachine.StartClawGameResp\x12c\n" +
	"\x14AddTouchedItemRecord\x12$.clawMachine.AddTouchedItemRecordReq\x1a%.clawMachine.AddTouchedItemRecordResp\x12T\n" +
	"\x0fCreateClawItems\x12\x1f.clawMachine.CreateClawItemsReq\x1a .clawMachine.CreateClawItemsResp\x12T\n" +
	"\x0fDeleteClawItems\x12\x1f.clawMachine.DeleteClawItemsReq\x1a .clawMachine.DeleteClawItemsResp\x12u\n" +
	"\x1aUpdateClawMachineTargetRTP\x12*.clawMachine.UpdateClawMachineTargetRTPReq\x1a+.clawMachine.UpdateClawMachineTargetRTPRespB8Z6github.com/Richard-inter/game/pkg/protocol/clawMachineb\x06proto3"

var (
	file_clawMachine_clawMachine_proto_rawDescOnce sync.Once
	file_clawMachine_clawMachine_proto_rawDescData []byte
)

func file_clawMachine_clawMachine_proto_rawDescGZIP() []byte {
	file_clawMachine_clawMachine_proto_rawDescOnce.Do(func() {
		file_clawMachine_clawMachine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clawMachine_clawMachine_proto_rawDesc), len(file_clawMachine_clawMachine_proto_rawDesc)))
	})
	return file_clawMachine_clawMachine_proto_rawDescData
}

var file_clawMachine_clawMachine_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_clawMachine_clawMachine_proto_goTypes = []any{
	(*Item)(nil),                           // 0: clawMachine.Item
	(*ClawMachine)(nil),                    // 1: clawMachine.ClawMachine
	(*ClawPlayer)(nil),                     // 2: clawMachine.ClawPlayer
	(*Items)(nil),                          // 3: clawMachine.Items
	(*CreateClawMachineReq)(nil),           // 4: clawMachine.CreateClawMachineReq
	(*CreateClawMachineResp)(nil),          // 5: clawMachine.CreateClawMachineResp
	(*StartClawGameReq)(nil),               // 6: clawMachine.StartClawGameReq
	(*ClawResult)(nil),                     // 7: clawMachine.ClawResult
	(*StartClawGameResp)(nil),              // 8: clawMachine.StartClawGameResp
	(*GetClawPlayerInfoReq)(nil),           // 9: clawMachine.GetClawPlayerInfoReq
	(*GetClawPlayerInfoResp)(nil),          // 10: clawMachine.GetClawPlayerInfoResp
	(*GetClawMachineInfoReq)(nil),          // 11: clawMachine.GetClawMachineInfoReq
	(*GetClawMachineInfoResp)(nil),         // 12: clawMachine.GetClawMachineInfoResp
	(*CreateItemReq)(nil),                  // 13: clawMachine.CreateItemReq
	(*CreateClawItemsReq)(nil),             // 14: clawMachine.CreateClawItemsReq
	(*CreateClawItemsResp)(nil),            // 15: clawMachine.CreateClawItemsResp
	(*CreateClawPlayerReq)(nil),            // 16: clawMachine.CreateClawPlayerReq
	(*CreateClawPlayerResp)(nil),           // 17: clawMachine.CreateClawPlayerResp
	(*AdjustPlayerCoinReq)(nil),            // 18: clawMachine.AdjustPlayerCoinReq
	(*AdjustPlayerCoinResp)(nil),           // 19: clawMachine.AdjustPlayerCoinResp
	(*AdjustPlayerDiamondReq)(nil),         // 20: clawMachine.AdjustPlayerDiamondReq
	(*AdjustPlayerDiamondResp)(nil),        // 21: clawMachine.AdjustPlayerDiamondResp
	(*AddTouchedItemRecordReq)(nil),        // 22: clawMachine.AddTouchedItemRecordReq
	(*AddTouchedItemRecordResp)(nil),       // 23: clawMachine.AddTouchedItemRecordResp
	(*DeleteClawPlayerReq)(nil),            // 24: clawMachine.DeleteClawPlayerReq
	(*DeleteClawPlayerResp)(nil),           // 25: clawMachine.DeleteClawPlayerResp
	(*GetGameHistoryReq)(nil),              // 26: clawMachine.GetGameHistoryReq
	(*ClawMachineGameRecord)(nil),          // 27: clawMachine.ClawMachineGameRecord
	(*GetGameHistoryResp)(nil),             // 28: clawMachine.GetGameHistoryResp
	(*UpdateClawMachineItemsReq)(nil),      // 29: clawMachine.UpdateClawMachineItemsReq
	(*UpdateClawMachineItemsResp)(nil),     // 30: clawMachine.UpdateClawMachineItemsResp
	(*DeleteClawMachineReq)(nil),           // 31: clawMachine.DeleteClawMachineReq
	(*DeleteClawMachineResp)(nil),          // 32: clawMachine.DeleteClawMachineResp
	(*DeleteClawItemsReq)(nil),             // 33: clawMachine.DeleteClawItemsReq
	(*DeleteClawItemsResp)(nil),            // 34: clawMachine.DeleteClawItemsResp
	(*UpdateClawMachineTargetRTPReq)(nil),  // 35: clawMachine.UpdateClawMachineTargetRTPReq
	(*UpdateClawMachineTargetRTPResp)(nil), // 36: clawMachine.UpdateClawMachineTargetRTPResp
	(*player.Player)(nil),                  // 37: player.Player
}
var file_clawMachine_clawMachine_proto_depIdxs = []int32{
	0,  // 0: clawMachine.ClawMachine.items:type_name -> clawMachine.Item
	37, // 1: clawMachine.ClawPlayer.basePlayer:type_name -> player.Player
	3,  // 2: clawMachine.CreateClawMachineReq.items:type_name -> clawMachine.Items
	1,  // 3: clawMachine.CreateClawMachineResp.machine:type_name -> clawMachine.ClawMachine
	7,  // 4: clawMachine.StartClawGameResp.results:type_name -> clawMachine.ClawResult
	2,  // 5: clawMachine.GetClawPlayerInfoResp.player:type_name -> clawMachine.ClawPlayer
	1,  // 6: clawMachine.GetClawMachineInfoResp.machine:type_name -> clawMachine.ClawMachine
	13, // 7: clawMachine.CreateClawItemsReq.clawItems:type_name -> clawMachine.CreateItemReq
	0,  // 8: clawMachine.CreateClawItemsResp.clawItems:type_name -> clawMachine.Item
	2,  // 9: clawMachine.CreateClawPlayerReq.player:type_name -> clawMachine.ClawPlayer
	2,  // 10: clawMachine.CreateClawPlayerResp.player:type_name -> clawMachine.ClawPlayer
	27, // 11: clawMachine.GetGameHistoryResp.gameRecords:type_name -> clawMachine.ClawMachineGameRecord
	3,  // 12: clawMachine.UpdateClawMachineItemsReq.items:type_name -> clawMachine.Items
	16, // 13: clawMachine.ClawMachineService.CreateClawPlayer:input_type -> clawMachine.CreateClawPlayerReq
	9,  // 14: clawMachine.ClawMachineService.GetClawPlayerInfo:input_type -> clawMachine.GetClawPlayerInfoReq
	24, // 15: clawMachine.ClawMachineService.DeleteClawPlayer:input_type -> clawMachine.DeleteClawPlayerReq
	18, // 16: clawMachine.ClawMachineService.AdjustPlayerCoin:input_type -> clawMachine.AdjustPlayerCoinReq
	20, // 17: clawMachine.ClawMachineService.AdjustPlayerDiamond:input_type -> clawMachine.AdjustPlayerDiamondReq
	26, // 18: clawMachine.ClawMachineService.GetGameHistory:input_type -> clawMachine.GetGameHistoryReq
	4,  // 19: clawMachine.ClawMachineService.CreateClawMachine:input_type -> clawMachine.CreateClawMachineReq
	11, // 20: clawMachine.ClawMachineService.GetClawMachineInfo:input_type -> clawMachine.GetClawMachineInfoReq
	29, // 21: clawMachine.ClawMachineService.UpdateClawMachineItems:input_type -> clawMachine.UpdateClawMachineItemsReq
	31, // 22: clawMachine.ClawMachineService.DeleteClawMachine:input_type -> clawMachine.DeleteClawMachineReq
	6,  // 23: clawMachine.ClawMachineService.StartClawGame:input_type -> clawMachine.StartClawGameReq
	22, // 24: clawMachine.ClawMachineService.AddTouchedItemRecord:input_type -> clawMachine.AddTouchedItemRecordReq
	14, // 25: clawMachine.ClawMachineService.CreateClawItems:input_type -> clawMachine.CreateClawItemsReq
	33, // 26: clawMachine.ClawMachineService.DeleteClawItems:input_type -> clawMachine.DeleteClawItemsReq
	35, // 27: clawMachine.ClawMachineService.UpdateClawMachineTargetRTP:input_type -> clawMachine.UpdateClawMachineTargetRTPReq
	17, // 28: clawMachine.ClawMachineService.CreateClawPlayer:output_type -> clawMachine.CreateClawPlayerResp
	10, // 29: clawMachine.ClawMachineService.GetClawPlayerInfo:output_type -> clawMachine.GetClawPlayerInfoResp
	25, // 30: clawMachine.ClawMachineService.DeleteClawPlayer:output_type -> clawMachine.DeleteClawPlayerResp
	19, // 31: clawMachine.ClawMachineService.AdjustPlayerCoin:output_type -> clawMachine.AdjustPlayerCoinResp
	21, // 32: clawMachine.ClawMachineService.AdjustPlayerDiamond:output_type -> clawMachine.AdjustPlayerDiamondResp
	28, // 33: clawMachine.ClawMachineService.GetGameHistory:output_type -> clawMachine.GetGameHistoryResp
	5,  // 34: clawMachine.ClawMachineService.CreateClawMachine:output_type -> clawMachine.CreateClawMachineResp
	12, // 35: clawMachine.ClawMachineService.GetClawMachineInfo:output_type -> clawMachine.GetClawMachineInfoResp
	30, // 36: clawMachine.ClawMachineService.UpdateClawMachineItems:output_type -> clawMachine.UpdateClawMachineItemsResp
	32, // 37: clawMachine.ClawMachineService.DeleteClawMachine:output_type -> clawMachine.DeleteClawMachineResp
	8,  // 38: clawMachine.ClawMachineService.StartClawGame:output_type -> clawMachine.StartClawGameResp
	23, // 39: clawMachine.ClawMachineService.AddTouchedItemRecord:output_type -> clawMachine.AddTouchedItemRecordResp
	15, // 40: clawMachine.ClawMachineService.CreateClawItems:output_type -> clawMachine.CreateClawItemsResp
	34, // 41: clawMachine.ClawMachineService.DeleteClawItems:output_type -> clawMachine.DeleteClawItemsResp
	36, // 42: clawMachine.ClawMachineService.UpdateClawMachineTargetRTP:output_type -> clawMachine.UpdateClawMachineTargetRTPResp
	28, // [28:43] is the sub-list for method output_type
	13, // [13:28] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_clawMachine_clawMachine_proto_init() }
func file_clawMachine_clawMachine_proto_init() {
	if File_clawMachine_clawMachine_proto != nil {
		return
	}
	file_clawMachine_clawMachine_proto_msgTypes[7].OneofWrappers = []any{}
	file_clawMachine_clawMachine_proto_msgTypes[22].OneofWrappers = []any{}
	file_clawMachine_clawMachine_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clawMachine_clawMachine_proto_rawDesc), len(file_clawMachine_clawMachine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clawMachine_clawMachine_proto_goTypes,
		DependencyIndexes: file_clawMachine_clawMachine_proto_depIdxs,
		MessageInfos:      file_clawMachine_clawMachine_proto_msgTypes,
	}.Build()
	File_clawMachine_clawMachine_proto = out.File
	file_clawMachine_clawMachine_proto_goTypes = nil
	file_clawMachine_clawMachine_proto_depIdxs = nil
}
