// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: clawMachine/clawMachine.proto

package clawMachine

import (
	player "github.com/Richard-inter/game/pkg/protocol/player"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemID        int64                  `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rarity        string                 `protobuf:"bytes,3,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Weight        int64                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetItemID() int64 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *Item) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type ClawMachine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineID     int64                  `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Items         []*Item                `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClawMachine) Reset() {
	*x = ClawMachine{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClawMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClawMachine) ProtoMessage() {}

func (x *ClawMachine) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClawMachine.ProtoReflect.Descriptor instead.
func (*ClawMachine) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{1}
}

func (x *ClawMachine) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

func (x *ClawMachine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClawMachine) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ClawMachine) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ClawPlayer struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BasePlayer *player.Player         `protobuf:"bytes,1,opt,name=basePlayer,proto3" json:"basePlayer,omitempty"`
	// game specific attributes
	Coin          int64 `protobuf:"varint,2,opt,name=coin,proto3" json:"coin,omitempty"`
	Diamond       int64 `protobuf:"varint,3,opt,name=diamond,proto3" json:"diamond,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClawPlayer) Reset() {
	*x = ClawPlayer{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClawPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClawPlayer) ProtoMessage() {}

func (x *ClawPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClawPlayer.ProtoReflect.Descriptor instead.
func (*ClawPlayer) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{2}
}

func (x *ClawPlayer) GetBasePlayer() *player.Player {
	if x != nil {
		return x.BasePlayer
	}
	return nil
}

func (x *ClawPlayer) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *ClawPlayer) GetDiamond() int64 {
	if x != nil {
		return x.Diamond
	}
	return 0
}

type Items struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemID        int64                  `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Items) Reset() {
	*x = Items{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{3}
}

func (x *Items) GetItemID() int64 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

type CreateClawMachineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Items         []*Items               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClawMachineReq) Reset() {
	*x = CreateClawMachineReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClawMachineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClawMachineReq) ProtoMessage() {}

func (x *CreateClawMachineReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClawMachineReq.ProtoReflect.Descriptor instead.
func (*CreateClawMachineReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{4}
}

func (x *CreateClawMachineReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClawMachineReq) GetItems() []*Items {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateClawMachineReq) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateClawMachineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *ClawMachine           `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClawMachineResp) Reset() {
	*x = CreateClawMachineResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClawMachineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClawMachineResp) ProtoMessage() {}

func (x *CreateClawMachineResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClawMachineResp.ProtoReflect.Descriptor instead.
func (*CreateClawMachineResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{5}
}

func (x *CreateClawMachineResp) GetMachine() *ClawMachine {
	if x != nil {
		return x.Machine
	}
	return nil
}

type StartClawGameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	MachineID     int64                  `protobuf:"varint,2,opt,name=machineID,proto3" json:"machineID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartClawGameReq) Reset() {
	*x = StartClawGameReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartClawGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartClawGameReq) ProtoMessage() {}

func (x *StartClawGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartClawGameReq.ProtoReflect.Descriptor instead.
func (*StartClawGameReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{6}
}

func (x *StartClawGameReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *StartClawGameReq) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

type ClawResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemID        int64                  `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Catched       bool                   `protobuf:"varint,2,opt,name=catched,proto3" json:"catched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClawResult) Reset() {
	*x = ClawResult{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClawResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClawResult) ProtoMessage() {}

func (x *ClawResult) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClawResult.ProtoReflect.Descriptor instead.
func (*ClawResult) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{7}
}

func (x *ClawResult) GetItemID() int64 {
	if x != nil {
		return x.ItemID
	}
	return 0
}

func (x *ClawResult) GetCatched() bool {
	if x != nil {
		return x.Catched
	}
	return false
}

type StartClawGameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameID        int64                  `protobuf:"varint,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	Results       []*ClawResult          `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartClawGameResp) Reset() {
	*x = StartClawGameResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartClawGameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartClawGameResp) ProtoMessage() {}

func (x *StartClawGameResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartClawGameResp.ProtoReflect.Descriptor instead.
func (*StartClawGameResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{8}
}

func (x *StartClawGameResp) GetGameID() int64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *StartClawGameResp) GetResults() []*ClawResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetClawPlayerInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClawPlayerInfoReq) Reset() {
	*x = GetClawPlayerInfoReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClawPlayerInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClawPlayerInfoReq) ProtoMessage() {}

func (x *GetClawPlayerInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClawPlayerInfoReq.ProtoReflect.Descriptor instead.
func (*GetClawPlayerInfoReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{9}
}

func (x *GetClawPlayerInfoReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

type GetClawPlayerInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *ClawPlayer            `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClawPlayerInfoResp) Reset() {
	*x = GetClawPlayerInfoResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClawPlayerInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClawPlayerInfoResp) ProtoMessage() {}

func (x *GetClawPlayerInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClawPlayerInfoResp.ProtoReflect.Descriptor instead.
func (*GetClawPlayerInfoResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{10}
}

func (x *GetClawPlayerInfoResp) GetPlayer() *ClawPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

type GetClawMachineInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineID     int64                  `protobuf:"varint,1,opt,name=machineID,proto3" json:"machineID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClawMachineInfoReq) Reset() {
	*x = GetClawMachineInfoReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClawMachineInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClawMachineInfoReq) ProtoMessage() {}

func (x *GetClawMachineInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClawMachineInfoReq.ProtoReflect.Descriptor instead.
func (*GetClawMachineInfoReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{11}
}

func (x *GetClawMachineInfoReq) GetMachineID() int64 {
	if x != nil {
		return x.MachineID
	}
	return 0
}

type GetClawMachineInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *ClawMachine           `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClawMachineInfoResp) Reset() {
	*x = GetClawMachineInfoResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClawMachineInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClawMachineInfoResp) ProtoMessage() {}

func (x *GetClawMachineInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClawMachineInfoResp.ProtoReflect.Descriptor instead.
func (*GetClawMachineInfoResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{12}
}

func (x *GetClawMachineInfoResp) GetMachine() *ClawMachine {
	if x != nil {
		return x.Machine
	}
	return nil
}

type CreateItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rarity        string                 `protobuf:"bytes,2,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Weight        int64                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemReq) Reset() {
	*x = CreateItemReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemReq) ProtoMessage() {}

func (x *CreateItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemReq.ProtoReflect.Descriptor instead.
func (*CreateItemReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{13}
}

func (x *CreateItemReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateItemReq) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *CreateItemReq) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type CreateClawItemsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClawItems     []*CreateItemReq       `protobuf:"bytes,1,rep,name=clawItems,proto3" json:"clawItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClawItemsReq) Reset() {
	*x = CreateClawItemsReq{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClawItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClawItemsReq) ProtoMessage() {}

func (x *CreateClawItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClawItemsReq.ProtoReflect.Descriptor instead.
func (*CreateClawItemsReq) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{14}
}

func (x *CreateClawItemsReq) GetClawItems() []*CreateItemReq {
	if x != nil {
		return x.ClawItems
	}
	return nil
}

type CreateClawItemsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClawItems     []*Item                `protobuf:"bytes,2,rep,name=clawItems,proto3" json:"clawItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClawItemsResp) Reset() {
	*x = CreateClawItemsResp{}
	mi := &file_clawMachine_clawMachine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClawItemsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClawItemsResp) ProtoMessage() {}

func (x *CreateClawItemsResp) ProtoReflect() protoreflect.Message {
	mi := &file_clawMachine_clawMachine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClawItemsResp.ProtoReflect.Descriptor instead.
func (*CreateClawItemsResp) Descriptor() ([]byte, []int) {
	return file_clawMachine_clawMachine_proto_rawDescGZIP(), []int{15}
}

func (x *CreateClawItemsResp) GetClawItems() []*Item {
	if x != nil {
		return x.ClawItems
	}
	return nil
}

var File_clawMachine_clawMachine_proto protoreflect.FileDescriptor

const file_clawMachine_clawMachine_proto_rawDesc = "" +
	"\n" +
	"\x1dclawMachine/clawMachine.proto\x12\vclawMachine\x1a\x13player/player.proto\"b\n" +
	"\x04Item\x12\x16\n" +
	"\x06itemID\x18\x01 \x01(\x03R\x06itemID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06rarity\x18\x03 \x01(\tR\x06rarity\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x03R\x06weight\"~\n" +
	"\vClawMachine\x12\x1c\n" +
	"\tmachineID\x18\x01 \x01(\x03R\tmachineID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x05items\x18\x03 \x03(\v2\x11.clawMachine.ItemR\x05items\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\"j\n" +
	"\n" +
	"ClawPlayer\x12.\n" +
	"\n" +
	"basePlayer\x18\x01 \x01(\v2\x0e.player.PlayerR\n" +
	"basePlayer\x12\x12\n" +
	"\x04coin\x18\x02 \x01(\x03R\x04coin\x12\x18\n" +
	"\adiamond\x18\x03 \x01(\x03R\adiamond\"\x1f\n" +
	"\x05Items\x12\x16\n" +
	"\x06itemID\x18\x01 \x01(\x03R\x06itemID\"j\n" +
	"\x14CreateClawMachineReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.clawMachine.ItemsR\x05items\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\"K\n" +
	"\x15CreateClawMachineResp\x122\n" +
	"\amachine\x18\x01 \x01(\v2\x18.clawMachine.ClawMachineR\amachine\"L\n" +
	"\x10StartClawGameReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\x12\x1c\n" +
	"\tmachineID\x18\x02 \x01(\x03R\tmachineID\">\n" +
	"\n" +
	"ClawResult\x12\x16\n" +
	"\x06itemID\x18\x01 \x01(\x03R\x06itemID\x12\x18\n" +
	"\acatched\x18\x02 \x01(\bR\acatched\"^\n" +
	"\x11StartClawGameResp\x12\x16\n" +
	"\x06gameID\x18\x01 \x01(\x03R\x06gameID\x121\n" +
	"\aresults\x18\x02 \x03(\v2\x17.clawMachine.ClawResultR\aresults\"2\n" +
	"\x14GetClawPlayerInfoReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\"H\n" +
	"\x15GetClawPlayerInfoResp\x12/\n" +
	"\x06player\x18\x01 \x01(\v2\x17.clawMachine.ClawPlayerR\x06player\"5\n" +
	"\x15GetClawMachineInfoReq\x12\x1c\n" +
	"\tmachineID\x18\x01 \x01(\x03R\tmachineID\"L\n" +
	"\x16GetClawMachineInfoResp\x122\n" +
	"\amachine\x18\x01 \x01(\v2\x18.clawMachine.ClawMachineR\amachine\"S\n" +
	"\rCreateItemReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06rarity\x18\x02 \x01(\tR\x06rarity\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x03R\x06weight\"N\n" +
	"\x12CreateClawItemsReq\x128\n" +
	"\tclawItems\x18\x01 \x03(\v2\x1a.clawMachine.CreateItemReqR\tclawItems\"F\n" +
	"\x13CreateClawItemsResp\x12/\n" +
	"\tclawItems\x18\x02 \x03(\v2\x11.clawMachine.ItemR\tclawItems2\xd1\x03\n" +
	"\x12ClawMachineService\x12Z\n" +
	"\x11CreateClawMachine\x12!.clawMachine.CreateClawMachineReq\x1a\".clawMachine.CreateClawMachineResp\x12]\n" +
	"\x12GetClawMachineInfo\x12\".clawMachine.GetClawMachineInfoReq\x1a#.clawMachine.GetClawMachineInfoResp\x12N\n" +
	"\rStartClawGame\x12\x1d.clawMachine.StartClawGameReq\x1a\x1e.clawMachine.StartClawGameResp\x12Z\n" +
	"\x11GetClawPlayerInfo\x12!.clawMachine.GetClawPlayerInfoReq\x1a\".clawMachine.GetClawPlayerInfoResp\x12T\n" +
	"\x0fCreateClawItems\x12\x1f.clawMachine.CreateClawItemsReq\x1a .clawMachine.CreateClawItemsRespB8Z6github.com/Richard-inter/game/pkg/protocol/clawMachineb\x06proto3"

var (
	file_clawMachine_clawMachine_proto_rawDescOnce sync.Once
	file_clawMachine_clawMachine_proto_rawDescData []byte
)

func file_clawMachine_clawMachine_proto_rawDescGZIP() []byte {
	file_clawMachine_clawMachine_proto_rawDescOnce.Do(func() {
		file_clawMachine_clawMachine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clawMachine_clawMachine_proto_rawDesc), len(file_clawMachine_clawMachine_proto_rawDesc)))
	})
	return file_clawMachine_clawMachine_proto_rawDescData
}

var file_clawMachine_clawMachine_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_clawMachine_clawMachine_proto_goTypes = []any{
	(*Item)(nil),                   // 0: clawMachine.Item
	(*ClawMachine)(nil),            // 1: clawMachine.ClawMachine
	(*ClawPlayer)(nil),             // 2: clawMachine.ClawPlayer
	(*Items)(nil),                  // 3: clawMachine.Items
	(*CreateClawMachineReq)(nil),   // 4: clawMachine.CreateClawMachineReq
	(*CreateClawMachineResp)(nil),  // 5: clawMachine.CreateClawMachineResp
	(*StartClawGameReq)(nil),       // 6: clawMachine.StartClawGameReq
	(*ClawResult)(nil),             // 7: clawMachine.ClawResult
	(*StartClawGameResp)(nil),      // 8: clawMachine.StartClawGameResp
	(*GetClawPlayerInfoReq)(nil),   // 9: clawMachine.GetClawPlayerInfoReq
	(*GetClawPlayerInfoResp)(nil),  // 10: clawMachine.GetClawPlayerInfoResp
	(*GetClawMachineInfoReq)(nil),  // 11: clawMachine.GetClawMachineInfoReq
	(*GetClawMachineInfoResp)(nil), // 12: clawMachine.GetClawMachineInfoResp
	(*CreateItemReq)(nil),          // 13: clawMachine.CreateItemReq
	(*CreateClawItemsReq)(nil),     // 14: clawMachine.CreateClawItemsReq
	(*CreateClawItemsResp)(nil),    // 15: clawMachine.CreateClawItemsResp
	(*player.Player)(nil),          // 16: player.Player
}
var file_clawMachine_clawMachine_proto_depIdxs = []int32{
	0,  // 0: clawMachine.ClawMachine.items:type_name -> clawMachine.Item
	16, // 1: clawMachine.ClawPlayer.basePlayer:type_name -> player.Player
	3,  // 2: clawMachine.CreateClawMachineReq.items:type_name -> clawMachine.Items
	1,  // 3: clawMachine.CreateClawMachineResp.machine:type_name -> clawMachine.ClawMachine
	7,  // 4: clawMachine.StartClawGameResp.results:type_name -> clawMachine.ClawResult
	2,  // 5: clawMachine.GetClawPlayerInfoResp.player:type_name -> clawMachine.ClawPlayer
	1,  // 6: clawMachine.GetClawMachineInfoResp.machine:type_name -> clawMachine.ClawMachine
	13, // 7: clawMachine.CreateClawItemsReq.clawItems:type_name -> clawMachine.CreateItemReq
	0,  // 8: clawMachine.CreateClawItemsResp.clawItems:type_name -> clawMachine.Item
	4,  // 9: clawMachine.ClawMachineService.CreateClawMachine:input_type -> clawMachine.CreateClawMachineReq
	11, // 10: clawMachine.ClawMachineService.GetClawMachineInfo:input_type -> clawMachine.GetClawMachineInfoReq
	6,  // 11: clawMachine.ClawMachineService.StartClawGame:input_type -> clawMachine.StartClawGameReq
	9,  // 12: clawMachine.ClawMachineService.GetClawPlayerInfo:input_type -> clawMachine.GetClawPlayerInfoReq
	14, // 13: clawMachine.ClawMachineService.CreateClawItems:input_type -> clawMachine.CreateClawItemsReq
	5,  // 14: clawMachine.ClawMachineService.CreateClawMachine:output_type -> clawMachine.CreateClawMachineResp
	12, // 15: clawMachine.ClawMachineService.GetClawMachineInfo:output_type -> clawMachine.GetClawMachineInfoResp
	8,  // 16: clawMachine.ClawMachineService.StartClawGame:output_type -> clawMachine.StartClawGameResp
	10, // 17: clawMachine.ClawMachineService.GetClawPlayerInfo:output_type -> clawMachine.GetClawPlayerInfoResp
	15, // 18: clawMachine.ClawMachineService.CreateClawItems:output_type -> clawMachine.CreateClawItemsResp
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_clawMachine_clawMachine_proto_init() }
func file_clawMachine_clawMachine_proto_init() {
	if File_clawMachine_clawMachine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clawMachine_clawMachine_proto_rawDesc), len(file_clawMachine_clawMachine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clawMachine_clawMachine_proto_goTypes,
		DependencyIndexes: file_clawMachine_clawMachine_proto_depIdxs,
		MessageInfos:      file_clawMachine_clawMachine_proto_msgTypes,
	}.Build()
	File_clawMachine_clawMachine_proto = out.File
	file_clawMachine_clawMachine_proto_goTypes = nil
	file_clawMachine_clawMachine_proto_depIdxs = nil
}
