// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clawMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AddTouchedItemRecordReq struct {
	_tab flatbuffers.Table
}

func GetRootAsAddTouchedItemRecordReq(buf []byte, offset flatbuffers.UOffsetT) *AddTouchedItemRecordReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AddTouchedItemRecordReq{}
	x.Init(buf, n+offset)
	return x
}

func FinishAddTouchedItemRecordReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAddTouchedItemRecordReq(buf []byte, offset flatbuffers.UOffsetT) *AddTouchedItemRecordReq {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AddTouchedItemRecordReq{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAddTouchedItemRecordReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AddTouchedItemRecordReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AddTouchedItemRecordReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AddTouchedItemRecordReq) GameId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AddTouchedItemRecordReq) MutateGameId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *AddTouchedItemRecordReq) ItemId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AddTouchedItemRecordReq) MutateItemId(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *AddTouchedItemRecordReq) Catched() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *AddTouchedItemRecordReq) MutateCatched(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func AddTouchedItemRecordReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func AddTouchedItemRecordReqAddGameId(builder *flatbuffers.Builder, gameId int64) {
	builder.PrependInt64Slot(0, gameId, 0)
}
func AddTouchedItemRecordReqAddItemId(builder *flatbuffers.Builder, itemId int64) {
	builder.PrependInt64Slot(1, itemId, 0)
}
func AddTouchedItemRecordReqAddCatched(builder *flatbuffers.Builder, catched bool) {
	builder.PrependBoolSlot(2, catched, false)
}
func AddTouchedItemRecordReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
