// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clawMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClawResult struct {
	_tab flatbuffers.Table
}

func GetRootAsClawResult(buf []byte, offset flatbuffers.UOffsetT) *ClawResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClawResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishClawResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsClawResult(buf []byte, offset flatbuffers.UOffsetT) *ClawResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClawResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedClawResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ClawResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClawResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ClawResult) ItemId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClawResult) MutateItemId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *ClawResult) Catched() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ClawResult) MutateCatched(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func ClawResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ClawResultAddItemId(builder *flatbuffers.Builder, itemId uint64) {
	builder.PrependUint64Slot(0, itemId, 0)
}
func ClawResultAddCatched(builder *flatbuffers.Builder, catched bool) {
	builder.PrependBoolSlot(1, catched, false)
}
func ClawResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
