// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clawMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetGameHistoryWsReq struct {
	_tab flatbuffers.Table
}

func GetRootAsGetGameHistoryWsReq(buf []byte, offset flatbuffers.UOffsetT) *GetGameHistoryWsReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetGameHistoryWsReq{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetGameHistoryWsReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetGameHistoryWsReq(buf []byte, offset flatbuffers.UOffsetT) *GetGameHistoryWsReq {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetGameHistoryWsReq{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetGameHistoryWsReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetGameHistoryWsReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetGameHistoryWsReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetGameHistoryWsReq) PlayerId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetGameHistoryWsReq) MutatePlayerId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func GetGameHistoryWsReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetGameHistoryWsReqAddPlayerId(builder *flatbuffers.Builder, playerId int64) {
	builder.PrependInt64Slot(0, playerId, 0)
}
func GetGameHistoryWsReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
