// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clawMachine

import "strconv"

type MessageType int8

const (
	MessageTypeStartClawGameReq         MessageType = 0
	MessageTypeStartClawGameResp        MessageType = 1
	MessageTypeAddTouchedItemRecordReq  MessageType = 2
	MessageTypeAddTouchedItemRecordResp MessageType = 3
	MessageTypeGetPlayerSnapshotReq     MessageType = 4
	MessageTypeGetPlayerSnapshotResp    MessageType = 5
)

var EnumNamesMessageType = map[MessageType]string{
	MessageTypeStartClawGameReq:         "StartClawGameReq",
	MessageTypeStartClawGameResp:        "StartClawGameResp",
	MessageTypeAddTouchedItemRecordReq:  "AddTouchedItemRecordReq",
	MessageTypeAddTouchedItemRecordResp: "AddTouchedItemRecordResp",
	MessageTypeGetPlayerSnapshotReq:     "GetPlayerSnapshotReq",
	MessageTypeGetPlayerSnapshotResp:    "GetPlayerSnapshotResp",
}

var EnumValuesMessageType = map[string]MessageType{
	"StartClawGameReq":         MessageTypeStartClawGameReq,
	"StartClawGameResp":        MessageTypeStartClawGameResp,
	"AddTouchedItemRecordReq":  MessageTypeAddTouchedItemRecordReq,
	"AddTouchedItemRecordResp": MessageTypeAddTouchedItemRecordResp,
	"GetPlayerSnapshotReq":     MessageTypeGetPlayerSnapshotReq,
	"GetPlayerSnapshotResp":    MessageTypeGetPlayerSnapshotResp,
}

func (v MessageType) String() string {
	if s, ok := EnumNamesMessageType[v]; ok {
		return s
	}
	return "MessageType(" + strconv.FormatInt(int64(v), 10) + ")"
}
