// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clawMachine

import "strconv"

type MessageType int8

const (
	MessageTypeStartClawGameReq         MessageType = 0
	MessageTypeStartClawGameResp        MessageType = 1
	MessageTypeAddTouchedItemRecordReq  MessageType = 2
	MessageTypeAddTouchedItemRecordResp MessageType = 3
	MessageTypeGetPlayerInfoWsReq       MessageType = 4
	MessageTypeGetPlayerInfoWsResp      MessageType = 5
	MessageTypeSpawnItemReq             MessageType = 6
	MessageTypeSpawnItemResp            MessageType = 7
	MessageTypeErrorResp                MessageType = 100
)

var EnumNamesMessageType = map[MessageType]string{
	MessageTypeStartClawGameReq:         "StartClawGameReq",
	MessageTypeStartClawGameResp:        "StartClawGameResp",
	MessageTypeAddTouchedItemRecordReq:  "AddTouchedItemRecordReq",
	MessageTypeAddTouchedItemRecordResp: "AddTouchedItemRecordResp",
	MessageTypeGetPlayerInfoWsReq:       "GetPlayerInfoWsReq",
	MessageTypeGetPlayerInfoWsResp:      "GetPlayerInfoWsResp",
	MessageTypeSpawnItemReq:             "SpawnItemReq",
	MessageTypeSpawnItemResp:            "SpawnItemResp",
	MessageTypeErrorResp:                "ErrorResp",
}

var EnumValuesMessageType = map[string]MessageType{
	"StartClawGameReq":         MessageTypeStartClawGameReq,
	"StartClawGameResp":        MessageTypeStartClawGameResp,
	"AddTouchedItemRecordReq":  MessageTypeAddTouchedItemRecordReq,
	"AddTouchedItemRecordResp": MessageTypeAddTouchedItemRecordResp,
	"GetPlayerInfoWsReq":       MessageTypeGetPlayerInfoWsReq,
	"GetPlayerInfoWsResp":      MessageTypeGetPlayerInfoWsResp,
	"SpawnItemReq":             MessageTypeSpawnItemReq,
	"SpawnItemResp":            MessageTypeSpawnItemResp,
	"ErrorResp":                MessageTypeErrorResp,
}

func (v MessageType) String() string {
	if s, ok := EnumNamesMessageType[v]; ok {
		return s
	}
	return "MessageType(" + strconv.FormatInt(int64(v), 10) + ")"
}
