// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clawMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlayerSnapshot struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayerSnapshot(buf []byte, offset flatbuffers.UOffsetT) *PlayerSnapshot {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayerSnapshot{}
	x.Init(buf, n+offset)
	return x
}

func FinishPlayerSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPlayerSnapshot(buf []byte, offset flatbuffers.UOffsetT) *PlayerSnapshot {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PlayerSnapshot{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPlayerSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PlayerSnapshot) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayerSnapshot) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayerSnapshot) PlayerId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerSnapshot) MutatePlayerId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *PlayerSnapshot) Coin() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerSnapshot) MutateCoin(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *PlayerSnapshot) Diamond() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayerSnapshot) MutateDiamond(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func PlayerSnapshotStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func PlayerSnapshotAddPlayerId(builder *flatbuffers.Builder, playerId uint64) {
	builder.PrependUint64Slot(0, playerId, 0)
}
func PlayerSnapshotAddCoin(builder *flatbuffers.Builder, coin int64) {
	builder.PrependInt64Slot(1, coin, 0)
}
func PlayerSnapshotAddDiamond(builder *flatbuffers.Builder, diamond int64) {
	builder.PrependInt64Slot(2, diamond, 0)
}
func PlayerSnapshotEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
