// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clawMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SpawnItemResp struct {
	_tab flatbuffers.Table
}

func GetRootAsSpawnItemResp(buf []byte, offset flatbuffers.UOffsetT) *SpawnItemResp {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SpawnItemResp{}
	x.Init(buf, n+offset)
	return x
}

func FinishSpawnItemRespBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSpawnItemResp(buf []byte, offset flatbuffers.UOffsetT) *SpawnItemResp {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SpawnItemResp{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSpawnItemRespBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SpawnItemResp) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SpawnItemResp) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SpawnItemResp) Items(j int) int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *SpawnItemResp) ItemsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SpawnItemResp) MutateItems(j int, n int64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func SpawnItemRespStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SpawnItemRespAddItems(builder *flatbuffers.Builder, items flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(items), 0)
}
func SpawnItemRespStartItemsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func SpawnItemRespEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
