// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clawMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SpawnItemReq struct {
	_tab flatbuffers.Table
}

func GetRootAsSpawnItemReq(buf []byte, offset flatbuffers.UOffsetT) *SpawnItemReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SpawnItemReq{}
	x.Init(buf, n+offset)
	return x
}

func FinishSpawnItemReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSpawnItemReq(buf []byte, offset flatbuffers.UOffsetT) *SpawnItemReq {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SpawnItemReq{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSpawnItemReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SpawnItemReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SpawnItemReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SpawnItemReq) MachineId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SpawnItemReq) MutateMachineId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func SpawnItemReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SpawnItemReqAddMachineId(builder *flatbuffers.Builder, machineId int64) {
	builder.PrependInt64Slot(0, machineId, 0)
}
func SpawnItemReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
