// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clawMachine

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StartClawGameReq struct {
	_tab flatbuffers.Table
}

func GetRootAsStartClawGameReq(buf []byte, offset flatbuffers.UOffsetT) *StartClawGameReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StartClawGameReq{}
	x.Init(buf, n+offset)
	return x
}

func FinishStartClawGameReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStartClawGameReq(buf []byte, offset flatbuffers.UOffsetT) *StartClawGameReq {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StartClawGameReq{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStartClawGameReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StartClawGameReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StartClawGameReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StartClawGameReq) PlayerId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StartClawGameReq) MutatePlayerId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *StartClawGameReq) MachineId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StartClawGameReq) MutateMachineId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func StartClawGameReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func StartClawGameReqAddPlayerId(builder *flatbuffers.Builder, playerId uint64) {
	builder.PrependUint64Slot(0, playerId, 0)
}
func StartClawGameReqAddMachineId(builder *flatbuffers.Builder, machineId uint64) {
	builder.PrependUint64Slot(1, machineId, 0)
}
func StartClawGameReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
