// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: player/player.proto

package player

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_player_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_player_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_player_player_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *Player) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type CreatePlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerReq) Reset() {
	*x = CreatePlayerReq{}
	mi := &file_player_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerReq) ProtoMessage() {}

func (x *CreatePlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_player_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerReq.ProtoReflect.Descriptor instead.
func (*CreatePlayerReq) Descriptor() ([]byte, []int) {
	return file_player_player_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePlayerReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type CreatePlayerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerResp) Reset() {
	*x = CreatePlayerResp{}
	mi := &file_player_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerResp) ProtoMessage() {}

func (x *CreatePlayerResp) ProtoReflect() protoreflect.Message {
	mi := &file_player_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerResp.ProtoReflect.Descriptor instead.
func (*CreatePlayerResp) Descriptor() ([]byte, []int) {
	return file_player_player_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePlayerResp) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type GetPlayerInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerID      int64                  `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerInfoReq) Reset() {
	*x = GetPlayerInfoReq{}
	mi := &file_player_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoReq) ProtoMessage() {}

func (x *GetPlayerInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_player_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoReq.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoReq) Descriptor() ([]byte, []int) {
	return file_player_player_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerInfoReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

type GetPlayerInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerInfoResp) Reset() {
	*x = GetPlayerInfoResp{}
	mi := &file_player_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoResp) ProtoMessage() {}

func (x *GetPlayerInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_player_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoResp.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoResp) Descriptor() ([]byte, []int) {
	return file_player_player_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlayerInfoResp) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

var File_player_player_proto protoreflect.FileDescriptor

const file_player_player_proto_rawDesc = "" +
	"\n" +
	"\x13player/player.proto\x12\x06player\"@\n" +
	"\x06Player\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\"-\n" +
	"\x0fCreatePlayerReq\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\":\n" +
	"\x10CreatePlayerResp\x12&\n" +
	"\x06player\x18\x01 \x01(\v2\x0e.player.PlayerR\x06player\".\n" +
	"\x10GetPlayerInfoReq\x12\x1a\n" +
	"\bplayerID\x18\x01 \x01(\x03R\bplayerID\";\n" +
	"\x11GetPlayerInfoResp\x12&\n" +
	"\x06player\x18\x01 \x01(\v2\x0e.player.PlayerR\x06player2\x98\x01\n" +
	"\rPlayerService\x12A\n" +
	"\fCreatePlayer\x12\x17.player.CreatePlayerReq\x1a\x18.player.CreatePlayerResp\x12D\n" +
	"\rGetPlayerInfo\x12\x18.player.GetPlayerInfoReq\x1a\x19.player.GetPlayerInfoRespB3Z1github.com/Richard-inter/game/pkg/protocol/playerb\x06proto3"

var (
	file_player_player_proto_rawDescOnce sync.Once
	file_player_player_proto_rawDescData []byte
)

func file_player_player_proto_rawDescGZIP() []byte {
	file_player_player_proto_rawDescOnce.Do(func() {
		file_player_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_player_proto_rawDesc), len(file_player_player_proto_rawDesc)))
	})
	return file_player_player_proto_rawDescData
}

var file_player_player_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_player_player_proto_goTypes = []any{
	(*Player)(nil),            // 0: player.Player
	(*CreatePlayerReq)(nil),   // 1: player.CreatePlayerReq
	(*CreatePlayerResp)(nil),  // 2: player.CreatePlayerResp
	(*GetPlayerInfoReq)(nil),  // 3: player.GetPlayerInfoReq
	(*GetPlayerInfoResp)(nil), // 4: player.GetPlayerInfoResp
}
var file_player_player_proto_depIdxs = []int32{
	0, // 0: player.CreatePlayerResp.player:type_name -> player.Player
	0, // 1: player.GetPlayerInfoResp.player:type_name -> player.Player
	1, // 2: player.PlayerService.CreatePlayer:input_type -> player.CreatePlayerReq
	3, // 3: player.PlayerService.GetPlayerInfo:input_type -> player.GetPlayerInfoReq
	2, // 4: player.PlayerService.CreatePlayer:output_type -> player.CreatePlayerResp
	4, // 5: player.PlayerService.GetPlayerInfo:output_type -> player.GetPlayerInfoResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_player_player_proto_init() }
func file_player_player_proto_init() {
	if File_player_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_player_proto_rawDesc), len(file_player_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_player_player_proto_goTypes,
		DependencyIndexes: file_player_player_proto_depIdxs,
		MessageInfos:      file_player_player_proto_msgTypes,
	}.Build()
	File_player_player_proto = out.File
	file_player_player_proto_goTypes = nil
	file_player_player_proto_depIdxs = nil
}
