// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: whackAMole/whackAMole.proto

package whackAMole

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhackAMolePlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhackAMolePlayer) Reset() {
	*x = WhackAMolePlayer{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhackAMolePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhackAMolePlayer) ProtoMessage() {}

func (x *WhackAMolePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhackAMolePlayer.ProtoReflect.Descriptor instead.
func (*WhackAMolePlayer) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{0}
}

func (x *WhackAMolePlayer) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *WhackAMolePlayer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type MoleWeightConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MoleType      string                 `protobuf:"bytes,2,opt,name=mole_type,json=moleType,proto3" json:"mole_type,omitempty"`
	Weight        int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoleWeightConfig) Reset() {
	*x = MoleWeightConfig{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoleWeightConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoleWeightConfig) ProtoMessage() {}

func (x *MoleWeightConfig) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoleWeightConfig.ProtoReflect.Descriptor instead.
func (*MoleWeightConfig) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{1}
}

func (x *MoleWeightConfig) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MoleWeightConfig) GetMoleType() string {
	if x != nil {
		return x.MoleType
	}
	return ""
}

func (x *MoleWeightConfig) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type LeaderBoard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Score         int64                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Rank          int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderBoard) Reset() {
	*x = LeaderBoard{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderBoard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderBoard) ProtoMessage() {}

func (x *LeaderBoard) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderBoard.ProtoReflect.Descriptor instead.
func (*LeaderBoard) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{2}
}

func (x *LeaderBoard) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *LeaderBoard) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LeaderBoard) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderBoard) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type CreateWhackAMolePlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWhackAMolePlayerReq) Reset() {
	*x = CreateWhackAMolePlayerReq{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWhackAMolePlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWhackAMolePlayerReq) ProtoMessage() {}

func (x *CreateWhackAMolePlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWhackAMolePlayerReq.ProtoReflect.Descriptor instead.
func (*CreateWhackAMolePlayerReq) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWhackAMolePlayerReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *CreateWhackAMolePlayerReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CreateWhackAMolePlayerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *WhackAMolePlayer      `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWhackAMolePlayerResp) Reset() {
	*x = CreateWhackAMolePlayerResp{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWhackAMolePlayerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWhackAMolePlayerResp) ProtoMessage() {}

func (x *CreateWhackAMolePlayerResp) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWhackAMolePlayerResp.ProtoReflect.Descriptor instead.
func (*CreateWhackAMolePlayerResp) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWhackAMolePlayerResp) GetPlayer() *WhackAMolePlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

type GetPlayerInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerInfoReq) Reset() {
	*x = GetPlayerInfoReq{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoReq) ProtoMessage() {}

func (x *GetPlayerInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoReq.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoReq) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlayerInfoReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type GetPlayerInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *WhackAMolePlayer      `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerInfoResp) Reset() {
	*x = GetPlayerInfoResp{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoResp) ProtoMessage() {}

func (x *GetPlayerInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoResp.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoResp) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{6}
}

func (x *GetPlayerInfoResp) GetPlayer() *WhackAMolePlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

type GetLeaderboardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardReq) Reset() {
	*x = GetLeaderboardReq{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardReq) ProtoMessage() {}

func (x *GetLeaderboardReq) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardReq.ProtoReflect.Descriptor instead.
func (*GetLeaderboardReq) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{7}
}

func (x *GetLeaderboardReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetLeaderboardResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leaderboard   []*LeaderBoard         `protobuf:"bytes,1,rep,name=leaderboard,proto3" json:"leaderboard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResp) Reset() {
	*x = GetLeaderboardResp{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResp) ProtoMessage() {}

func (x *GetLeaderboardResp) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResp.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResp) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{8}
}

func (x *GetLeaderboardResp) GetLeaderboard() []*LeaderBoard {
	if x != nil {
		return x.Leaderboard
	}
	return nil
}

type GetMoleWeightConfigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoleWeightConfigReq) Reset() {
	*x = GetMoleWeightConfigReq{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoleWeightConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoleWeightConfigReq) ProtoMessage() {}

func (x *GetMoleWeightConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoleWeightConfigReq.ProtoReflect.Descriptor instead.
func (*GetMoleWeightConfigReq) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{9}
}

func (x *GetMoleWeightConfigReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMoleWeightConfigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []*MoleWeightConfig    `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMoleWeightConfigResp) Reset() {
	*x = GetMoleWeightConfigResp{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMoleWeightConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoleWeightConfigResp) ProtoMessage() {}

func (x *GetMoleWeightConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoleWeightConfigResp.ProtoReflect.Descriptor instead.
func (*GetMoleWeightConfigResp) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{10}
}

func (x *GetMoleWeightConfigResp) GetConfig() []*MoleWeightConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateMoleWeightConfigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MoleType      string                 `protobuf:"bytes,1,opt,name=mole_type,json=moleType,proto3" json:"mole_type,omitempty"`
	Weight        int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMoleWeightConfigReq) Reset() {
	*x = CreateMoleWeightConfigReq{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMoleWeightConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMoleWeightConfigReq) ProtoMessage() {}

func (x *CreateMoleWeightConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMoleWeightConfigReq.ProtoReflect.Descriptor instead.
func (*CreateMoleWeightConfigReq) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{11}
}

func (x *CreateMoleWeightConfigReq) GetMoleType() string {
	if x != nil {
		return x.MoleType
	}
	return ""
}

func (x *CreateMoleWeightConfigReq) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type CreateMoleWeightConfigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *MoleWeightConfig      `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMoleWeightConfigResp) Reset() {
	*x = CreateMoleWeightConfigResp{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMoleWeightConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMoleWeightConfigResp) ProtoMessage() {}

func (x *CreateMoleWeightConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMoleWeightConfigResp.ProtoReflect.Descriptor instead.
func (*CreateMoleWeightConfigResp) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{12}
}

func (x *CreateMoleWeightConfigResp) GetConfig() *MoleWeightConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateMoleWeightConfigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MoleType      string                 `protobuf:"bytes,2,opt,name=mole_type,json=moleType,proto3" json:"mole_type,omitempty"`
	Weight        int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMoleWeightConfigReq) Reset() {
	*x = UpdateMoleWeightConfigReq{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMoleWeightConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMoleWeightConfigReq) ProtoMessage() {}

func (x *UpdateMoleWeightConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMoleWeightConfigReq.ProtoReflect.Descriptor instead.
func (*UpdateMoleWeightConfigReq) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateMoleWeightConfigReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMoleWeightConfigReq) GetMoleType() string {
	if x != nil {
		return x.MoleType
	}
	return ""
}

func (x *UpdateMoleWeightConfigReq) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type UpdateMoleWeightConfigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *MoleWeightConfig      `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMoleWeightConfigResp) Reset() {
	*x = UpdateMoleWeightConfigResp{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMoleWeightConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMoleWeightConfigResp) ProtoMessage() {}

func (x *UpdateMoleWeightConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMoleWeightConfigResp.ProtoReflect.Descriptor instead.
func (*UpdateMoleWeightConfigResp) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateMoleWeightConfigResp) GetConfig() *MoleWeightConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateScoreReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Score         int64                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScoreReq) Reset() {
	*x = UpdateScoreReq{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoreReq) ProtoMessage() {}

func (x *UpdateScoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoreReq.ProtoReflect.Descriptor instead.
func (*UpdateScoreReq) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateScoreReq) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *UpdateScoreReq) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type UpdateScoreResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScoreResp) Reset() {
	*x = UpdateScoreResp{}
	mi := &file_whackAMole_whackAMole_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoreResp) ProtoMessage() {}

func (x *UpdateScoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_whackAMole_whackAMole_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoreResp.ProtoReflect.Descriptor instead.
func (*UpdateScoreResp) Descriptor() ([]byte, []int) {
	return file_whackAMole_whackAMole_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateScoreResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_whackAMole_whackAMole_proto protoreflect.FileDescriptor

const file_whackAMole_whackAMole_proto_rawDesc = "" +
	"\n" +
	"\x1bwhackAMole/whackAMole.proto\x12\n" +
	"whackAMole\"K\n" +
	"\x10WhackAMolePlayer\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"W\n" +
	"\x10MoleWeightConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tmole_type\x18\x02 \x01(\tR\bmoleType\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\"p\n" +
	"\vLeaderBoard\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\"T\n" +
	"\x19CreateWhackAMolePlayerReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"R\n" +
	"\x1aCreateWhackAMolePlayerResp\x124\n" +
	"\x06player\x18\x01 \x01(\v2\x1c.whackAMole.WhackAMolePlayerR\x06player\"/\n" +
	"\x10GetPlayerInfoReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"I\n" +
	"\x11GetPlayerInfoResp\x124\n" +
	"\x06player\x18\x01 \x01(\v2\x1c.whackAMole.WhackAMolePlayerR\x06player\")\n" +
	"\x11GetLeaderboardReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"O\n" +
	"\x12GetLeaderboardResp\x129\n" +
	"\vleaderboard\x18\x01 \x03(\v2\x17.whackAMole.LeaderBoardR\vleaderboard\"(\n" +
	"\x16GetMoleWeightConfigReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"O\n" +
	"\x17GetMoleWeightConfigResp\x124\n" +
	"\x06config\x18\x01 \x03(\v2\x1c.whackAMole.MoleWeightConfigR\x06config\"P\n" +
	"\x19CreateMoleWeightConfigReq\x12\x1b\n" +
	"\tmole_type\x18\x01 \x01(\tR\bmoleType\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\"R\n" +
	"\x1aCreateMoleWeightConfigResp\x124\n" +
	"\x06config\x18\x01 \x01(\v2\x1c.whackAMole.MoleWeightConfigR\x06config\"`\n" +
	"\x19UpdateMoleWeightConfigReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tmole_type\x18\x02 \x01(\tR\bmoleType\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\"R\n" +
	"\x1aUpdateMoleWeightConfigResp\x124\n" +
	"\x06config\x18\x01 \x01(\v2\x1c.whackAMole.MoleWeightConfigR\x06config\"C\n" +
	"\x0eUpdateScoreReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x03R\x05score\"+\n" +
	"\x0fUpdateScoreResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x95\x05\n" +
	"\x11WhackAMoleService\x12g\n" +
	"\x16CreateWhackAMolePlayer\x12%.whackAMole.CreateWhackAMolePlayerReq\x1a&.whackAMole.CreateWhackAMolePlayerResp\x12L\n" +
	"\rGetPlayerInfo\x12\x1c.whackAMole.GetPlayerInfoReq\x1a\x1d.whackAMole.GetPlayerInfoResp\x12O\n" +
	"\x0eGetLeaderboard\x12\x1d.whackAMole.GetLeaderboardReq\x1a\x1e.whackAMole.GetLeaderboardResp\x12F\n" +
	"\vUpdateScore\x12\x1a.whackAMole.UpdateScoreReq\x1a\x1b.whackAMole.UpdateScoreResp\x12^\n" +
	"\x13GetMoleWeightConfig\x12\".whackAMole.GetMoleWeightConfigReq\x1a#.whackAMole.GetMoleWeightConfigResp\x12g\n" +
	"\x16CreateMoleWeightConfig\x12%.whackAMole.CreateMoleWeightConfigReq\x1a&.whackAMole.CreateMoleWeightConfigResp\x12g\n" +
	"\x16UpdateMoleWeightConfig\x12%.whackAMole.UpdateMoleWeightConfigReq\x1a&.whackAMole.UpdateMoleWeightConfigRespB7Z5github.com/Richard-inter/game/pkg/protocol/whackAMoleb\x06proto3"

var (
	file_whackAMole_whackAMole_proto_rawDescOnce sync.Once
	file_whackAMole_whackAMole_proto_rawDescData []byte
)

func file_whackAMole_whackAMole_proto_rawDescGZIP() []byte {
	file_whackAMole_whackAMole_proto_rawDescOnce.Do(func() {
		file_whackAMole_whackAMole_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whackAMole_whackAMole_proto_rawDesc), len(file_whackAMole_whackAMole_proto_rawDesc)))
	})
	return file_whackAMole_whackAMole_proto_rawDescData
}

var file_whackAMole_whackAMole_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_whackAMole_whackAMole_proto_goTypes = []any{
	(*WhackAMolePlayer)(nil),           // 0: whackAMole.WhackAMolePlayer
	(*MoleWeightConfig)(nil),           // 1: whackAMole.MoleWeightConfig
	(*LeaderBoard)(nil),                // 2: whackAMole.LeaderBoard
	(*CreateWhackAMolePlayerReq)(nil),  // 3: whackAMole.CreateWhackAMolePlayerReq
	(*CreateWhackAMolePlayerResp)(nil), // 4: whackAMole.CreateWhackAMolePlayerResp
	(*GetPlayerInfoReq)(nil),           // 5: whackAMole.GetPlayerInfoReq
	(*GetPlayerInfoResp)(nil),          // 6: whackAMole.GetPlayerInfoResp
	(*GetLeaderboardReq)(nil),          // 7: whackAMole.GetLeaderboardReq
	(*GetLeaderboardResp)(nil),         // 8: whackAMole.GetLeaderboardResp
	(*GetMoleWeightConfigReq)(nil),     // 9: whackAMole.GetMoleWeightConfigReq
	(*GetMoleWeightConfigResp)(nil),    // 10: whackAMole.GetMoleWeightConfigResp
	(*CreateMoleWeightConfigReq)(nil),  // 11: whackAMole.CreateMoleWeightConfigReq
	(*CreateMoleWeightConfigResp)(nil), // 12: whackAMole.CreateMoleWeightConfigResp
	(*UpdateMoleWeightConfigReq)(nil),  // 13: whackAMole.UpdateMoleWeightConfigReq
	(*UpdateMoleWeightConfigResp)(nil), // 14: whackAMole.UpdateMoleWeightConfigResp
	(*UpdateScoreReq)(nil),             // 15: whackAMole.UpdateScoreReq
	(*UpdateScoreResp)(nil),            // 16: whackAMole.UpdateScoreResp
}
var file_whackAMole_whackAMole_proto_depIdxs = []int32{
	0,  // 0: whackAMole.CreateWhackAMolePlayerResp.player:type_name -> whackAMole.WhackAMolePlayer
	0,  // 1: whackAMole.GetPlayerInfoResp.player:type_name -> whackAMole.WhackAMolePlayer
	2,  // 2: whackAMole.GetLeaderboardResp.leaderboard:type_name -> whackAMole.LeaderBoard
	1,  // 3: whackAMole.GetMoleWeightConfigResp.config:type_name -> whackAMole.MoleWeightConfig
	1,  // 4: whackAMole.CreateMoleWeightConfigResp.config:type_name -> whackAMole.MoleWeightConfig
	1,  // 5: whackAMole.UpdateMoleWeightConfigResp.config:type_name -> whackAMole.MoleWeightConfig
	3,  // 6: whackAMole.WhackAMoleService.CreateWhackAMolePlayer:input_type -> whackAMole.CreateWhackAMolePlayerReq
	5,  // 7: whackAMole.WhackAMoleService.GetPlayerInfo:input_type -> whackAMole.GetPlayerInfoReq
	7,  // 8: whackAMole.WhackAMoleService.GetLeaderboard:input_type -> whackAMole.GetLeaderboardReq
	15, // 9: whackAMole.WhackAMoleService.UpdateScore:input_type -> whackAMole.UpdateScoreReq
	9,  // 10: whackAMole.WhackAMoleService.GetMoleWeightConfig:input_type -> whackAMole.GetMoleWeightConfigReq
	11, // 11: whackAMole.WhackAMoleService.CreateMoleWeightConfig:input_type -> whackAMole.CreateMoleWeightConfigReq
	13, // 12: whackAMole.WhackAMoleService.UpdateMoleWeightConfig:input_type -> whackAMole.UpdateMoleWeightConfigReq
	4,  // 13: whackAMole.WhackAMoleService.CreateWhackAMolePlayer:output_type -> whackAMole.CreateWhackAMolePlayerResp
	6,  // 14: whackAMole.WhackAMoleService.GetPlayerInfo:output_type -> whackAMole.GetPlayerInfoResp
	8,  // 15: whackAMole.WhackAMoleService.GetLeaderboard:output_type -> whackAMole.GetLeaderboardResp
	16, // 16: whackAMole.WhackAMoleService.UpdateScore:output_type -> whackAMole.UpdateScoreResp
	10, // 17: whackAMole.WhackAMoleService.GetMoleWeightConfig:output_type -> whackAMole.GetMoleWeightConfigResp
	12, // 18: whackAMole.WhackAMoleService.CreateMoleWeightConfig:output_type -> whackAMole.CreateMoleWeightConfigResp
	14, // 19: whackAMole.WhackAMoleService.UpdateMoleWeightConfig:output_type -> whackAMole.UpdateMoleWeightConfigResp
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_whackAMole_whackAMole_proto_init() }
func file_whackAMole_whackAMole_proto_init() {
	if File_whackAMole_whackAMole_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whackAMole_whackAMole_proto_rawDesc), len(file_whackAMole_whackAMole_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whackAMole_whackAMole_proto_goTypes,
		DependencyIndexes: file_whackAMole_whackAMole_proto_depIdxs,
		MessageInfos:      file_whackAMole_whackAMole_proto_msgTypes,
	}.Build()
	File_whackAMole_whackAMole_proto = out.File
	file_whackAMole_whackAMole_proto_goTypes = nil
	file_whackAMole_whackAMole_proto_depIdxs = nil
}
